{
 "title": "[Iberdrola] Istio Ingress",
 "tags": [
  "iberdrola",
  "istio",
  "ingress",
  "k8s"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_pod_info,cluster)"
    }
   },
   {
    "name": "source_app",
    "label": "Source",
    "query": {
     "query": "label_values(istio_requests_total{cluster=~\"$cluster\"},source_app)"
    }
   },
   {
    "name": "destination_workload_namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(istio_requests_total{destination_workload_namespace!=\"unknown\", cluster=~\"$cluster\", source_app=~\"$source_app\"},destination_workload_namespace)"
    }
   },
   {
    "name": "destination_service_name",
    "label": "service",
    "query": {
     "query": "label_values(istio_requests_total{destination_service_name!=\"unknown\", source_app=~\"$source_app\", cluster=\"$cluster\"},destination_service_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests (period)",
   "type": "stat",
   "description": "This is the total number of requests made in this period (top-right period selected)",
   "gridPos": { "h": 3, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(istio_requests_total{cluster=~\"$cluster\", source_app=~\"$source_app\", destination_workload_namespace=~\"$destination_workload_namespace\",destination_service_name=~\"$destination_service_name\"}[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "% Success (period)",
   "type": "stat",
   "description": "This is the percentage of successful requests over the entire period in the top-right hand corner.\n\nNOTE: Ignoring 404s in this metric, since a 404 is a normal response for errant/invalid request.  This helps prevent this percentage from being affected by typical web scanners and security probes.",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(\r\n    istio_requests_total{response_code!~\"[4-5].*\", source_app=~\"$source_app\", destination_service_name=~\"$destination_service_name\", destination_workload_namespace=~\"$destination_workload_namespace\", cluster=\"$cluster\"}[${__range_s}s]\r\n      )\r\n   )   \r\n/ \r\n(\r\n  sum(\r\n    rate(\r\n      istio_requests_total{ source_app=~\"$source_app\", destination_service_name=~\"$destination_service_name\", destination_workload_namespace=~\"$destination_workload_namespace\", cluster=\"$cluster\"}[${__range_s}s]\r\n        )\r\n     ) - \r\n  (\r\n  sum(\r\n    rate(\r\n      istio_requests_total{response_code=~\"404|499\", source_app=~\"$source_app\", destination_service_name=~\"$destination_service_name\",destination_workload_namespace=~\"$destination_workload_namespace\", cluster=\"$cluster\"}[${__range_s}s]\r\n        )\r\n     ) \r\n  or vector(0)\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 1/2xx (2m)",
   "type": "stat",
   "description": "This is the number of successful requests in the last minute.  Successful being 1xx or 2xx by the standard HTTP definition.",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(istio_requests_total{cluster=~\"$cluster\", source_app=~\"$source_app\", destination_workload_namespace=~\"$destination_workload_namespace\",destination_service_name=~\"$destination_service_name\", response_code=~\"(1|2).*\" }[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 3xx (2m)",
   "type": "stat",
   "description": "This is the number of 3xx requests in the last minute.",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(istio_requests_total{cluster=~\"$cluster\", source_app=~\"$source_app\", destination_workload_namespace=~\"$destination_workload_namespace\",destination_service_name=~\"$destination_service_name\", response_code=~\"3.*\" }[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 4xx (2m)",
   "type": "stat",
   "description": "This is the number of 4xx requests in the last minute.",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(istio_requests_total{cluster=~\"$cluster\", source_app=~\"$source_app\", destination_workload_namespace=~\"$destination_workload_namespace\",destination_service_name=~\"$destination_service_name\", response_code=~\"4.*\" }[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 5xx (2m)",
   "type": "stat",
   "description": "This is the number of 5xx requests in the last minute.",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(sum(increase(istio_requests_total{cluster=~\"$cluster\", source_app=~\"$source_app\", destination_workload_namespace=~\"$destination_workload_namespace\",destination_service_name=~\"$destination_service_name\", response_code=~\"5.*\" }[$__range])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total HTTP Requests",
   "type": "timeseries",
   "description": "The total number of HTTP requests made within' each period",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(increase(istio_requests_total{cluster=~\"$cluster\", source_app=~\"$source_app\", destination_workload_namespace=~\"$destination_workload_namespace\",destination_service_name=~\"$destination_service_name\" }[5m]))) > 0",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "HTTP Requests / Scope",
   "type": "timeseries",
   "description": "This is a total number of requests broken down by the scope.  This can help get a sense of scale in relation to each other.",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(increase(istio_requests_total{cluster=~\"$cluster\", source_app=~\"$source_app\", destination_workload_namespace=~\"$destination_workload_namespace\",destination_service_name=~\"$destination_service_name\" }[5m])) by (source_app)) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Requests / Ingress",
   "type": "timeseries",
   "description": "This is a total number of requests broken down by the ingress.  This can help get a sense of scale in relation to each other.",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(sum(increase(istio_requests_total{cluster=~\"$cluster\", source_app=~\"$source_app\", destination_workload_namespace=~\"$destination_workload_namespace\",destination_service_name=~\"$destination_service_name\" }[5m])) by (destination_service_name)) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP Status Codes",
   "type": "timeseries",
   "description": "The breakdown of the various HTTP status codes of the requests handled within' this period that matches the variables chosen above.\n\nThis chart helps notice and dive into which service is having failures and of what kind.",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 3 },
   "targets": [
    {
     "expr": "round(sum(increase(istio_requests_total{cluster=~\"$cluster\", source_app=~\"$source_app\", destination_workload_namespace=~\"$destination_workload_namespace\",destination_service_name=~\"$destination_service_name\" }[5m])) by (response_code)) > 0",
     "legendFormat": "HTTP {{response_code}}"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Average request duration (seconds) by service",
   "type": "timeseries",
   "description": "Shows the average response size per service (bytes/response), grouped by destination service name.\n\nMore info: https://oneuptime.com/blog/post/2026-02-24-how-to-monitor-istio-request-bytes-and-istio-response-bytes-metrics/view#:~:text=How%20to%20Monitor%20istio_request_bytes%20and%20istio_response_bytes%20Metrics",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(istio_request_duration_milliseconds_sum{\r\n  reporter=\"source\",\r\n  cluster=\"$cluster\",\r\n  source_app=~\"$source_app\",\r\n  destination_service_name=~\"$destination_service_name\"\r\n}[5m])) by (destination_service_name)\r\n/\r\nsum(rate(istio_request_duration_milliseconds_count{\r\n  reporter=\"source\",\r\n  cluster=\"$cluster\",\r\n  source_app=~\"$source_app\",\r\n  destination_service_name=~\"$destination_service_name\"\r\n}[5m])) by (destination_service_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Latency (Average Percentiles)",
   "type": "timeseries",
   "description": "This graph can help assess and help us meet SLA requirements as far as the responsive time of our services.\n\nFor a more detailed latency graph broken out by ingress please open the closed tab at the bottom because it is very CPU intensive.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.99,\r\n  sum by (le)(\r\n    rate(\r\n        istio_request_duration_milliseconds_bucket{\r\n          cluster=~\"$cluster\",\r\n          source_app=~\"$source_app\",\r\n          destination_workload_namespace=~\"$destination_workload_namespace\",\r\n          destination_service_name=~\"$destination_service_name\",\r\n          response_code!~\"404|500|304|499\"\r\n        }[5m]\r\n    )\r\n  )\r\n)",
     "legendFormat": "0.99"
    },
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum by (le)(\r\n    rate(\r\n        istio_request_duration_milliseconds_bucket{\r\n          cluster=~\"$cluster\",\r\n          source_app=~\"$source_app\",\r\n          destination_workload_namespace=~\"$destination_workload_namespace\",\r\n          destination_service_name=~\"$destination_service_name\",\r\n          response_code!~\"404|500|304|499\"\r\n        }[5m]\r\n    )\r\n  )\r\n)",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(\r\n  0.90,\r\n  sum by (le)(\r\n    rate(\r\n        istio_request_duration_milliseconds_bucket{\r\n          cluster=~\"$cluster\",\r\n          source_app=~\"$source_app\",\r\n          destination_workload_namespace=~\"$destination_workload_namespace\",\r\n          destination_service_name=~\"$destination_service_name\",\r\n          response_code!~\"404|500|304|499\"\r\n        }[5m]\r\n    )\r\n  )\r\n)",
     "legendFormat": "0.90"
    },
    {
     "expr": "histogram_quantile(\r\n  0.75,\r\n  sum by (le)(\r\n    rate(\r\n        istio_request_duration_milliseconds_bucket{\r\n          cluster=~\"$cluster\",\r\n          source_app=~\"$source_app\",\r\n          destination_workload_namespace=~\"$destination_workload_namespace\",\r\n          destination_service_name=~\"$destination_service_name\",\r\n          response_code!~\"404|500|304|499\"\r\n        }[5m]\r\n    )\r\n  )\r\n)",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(\r\n  0.50,\r\n  sum by (le)(\r\n    rate(\r\n        istio_request_duration_milliseconds_bucket{\r\n          cluster=~\"$cluster\",\r\n          source_app=~\"$source_app\",\r\n          destination_workload_namespace=~\"$destination_workload_namespace\",\r\n          destination_service_name=~\"$destination_service_name\",\r\n          response_code!~\"404|500|304|499\"\r\n        }[5m]\r\n    )\r\n  )\r\n)",
     "legendFormat": "0.50"
    }
   ]
  },
  { "title": "Bandwith", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Combined Bandwidth",
   "type": "timeseries",
   "description": "Shows total bandwidth (incoming + outgoing) for the service, based on request and response bytes per second.\n\nMore info: https://oneuptime.com/blog/post/2026-02-24-how-to-monitor-istio-request-bytes-and-istio-response-bytes-metrics/view#:~:text=How%20to%20Monitor%20istio_request_bytes%20and%20istio_response_bytes%20Metrics",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "(\r\n  sum(rate(istio_request_bytes_sum{\r\n    reporter=\"source\",\r\n    cluster=\"$cluster\",\r\n    source_app=~\"$source_app\",\r\n    destination_service_name=~\"$destination_service_name\"\r\n  }[5m])) > 0 \r\n  +\r\n  sum(rate(istio_response_bytes_sum{\r\n    reporter=\"source\",\r\n    cluster=\"$cluster\",\r\n    source_app=~\"$source_app\",\r\n    destination_service_name=~\"$destination_service_name\"\r\n  }[5m])) > 0 \r\n) / 1024 / 1024",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "Average Request Size (in progress)",
   "type": "timeseries",
   "description": "Shows the average request size sent by the service (bytes/request), calculated from request byte totals divided by request counts.\n\nMore info: https://oneuptime.com/blog/post/2026-02-24-how-to-monitor-istio-request-bytes-and-istio-response-bytes-metrics/view#:~:text=How%20to%20Monitor%20istio_request_bytes%20and%20istio_response_bytes%20Metrics",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(istio_request_bytes_sum{\r\n  reporter=\"source\",\r\n  cluster=\"$cluster\",\r\n  source_app=~\"$source_app\",\r\n  destination_service_name=~\"$destination_service_name\"\r\n}[5m]))\r\n/\r\nsum(rate(istio_request_bytes_count{\r\n  reporter=\"source\",\r\n  cluster=\"$cluster\",\r\n  source_app=~\"$source_app\",\r\n  destination_service_name=~\"$destination_service_name\"\r\n}[5m]))",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "Average Response Size",
   "type": "timeseries",
   "description": "Shows the average response size sent by the service (bytes/response), based on response byte totals divided by response counts.\n\nMore info: https://oneuptime.com/blog/post/2026-02-24-how-to-monitor-istio-request-bytes-and-istio-response-bytes-metrics/view#:~:text=How%20to%20Monitor%20istio_request_bytes%20and%20istio_response_bytes%20Metrics",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(istio_response_bytes_sum{\r\n  reporter=\"source\",\r\n  cluster=\"$cluster\",\r\n  source_app=~\"$source_app\",\r\n  destination_service_name=~\"$destination_service_name\"\r\n}[5m])) > 0\r\n/\r\nsum(rate(istio_response_bytes_count{\r\n  reporter=\"source\",\r\n  cluster=\"$cluster\",\r\n  source_app=~\"$source_app\",\r\n  destination_service_name=~\"$destination_service_name\"\r\n}[5m])) > 0",
     "legendFormat": "{{destination_service_name}}"
    }
   ]
  },
  {
   "title": "Average Response Size by service",
   "type": "timeseries",
   "description": "Shows the average response size per service (bytes/response), grouped by destination service name.\n\nMore info: https://oneuptime.com/blog/post/2026-02-24-how-to-monitor-istio-request-bytes-and-istio-response-bytes-metrics/view#:~:text=How%20to%20Monitor%20istio_request_bytes%20and%20istio_response_bytes%20Metrics",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(istio_response_bytes_sum{\r\n  reporter=\"source\",\r\n  cluster=\"$cluster\",\r\n  source_app=~\"$source_app\",\r\n  destination_service_name=~\"$destination_service_name\"\r\n}[5m])) by (destination_service_name) > 0\r\n/\r\nsum(rate(istio_response_bytes_count{\r\n  reporter=\"source\",\r\n  cluster=\"$cluster\",\r\n  source_app=~\"$source_app\",\r\n  destination_service_name=~\"$destination_service_name\"\r\n}[5m])) by (destination_service_name) > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}