{
 "title": "Loki / Deletion",
 "tags": [ "loki" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "app_instance",
    "label": "app_instance",
    "query": "label_values(loki_build_info, app_instance)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(loki_build_info{app_instance=~\"$app_instance\"}, namespace)"
   },
   { "name": "loki_datasource", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Headlines", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Number of Pending Requests",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(loki_compactor_pending_delete_requests_count{app_instance=~\"$app_instance\", namespace=~\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Oldest Pending Request Age",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(loki_compactor_oldest_pending_delete_request_age_seconds{app_instance=~\"$app_instance\", namespace=~\"$namespace\"})"
    }
   ]
  },
  { "title": "Churn", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "# of Delete Requests (received - processed) ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(loki_compactor_delete_requests_received_total{app_instance=~\"$app_instance\", namespace=~\"$namespace\"} or on() vector(0)) - on () (loki_compactor_delete_requests_processed_total{app_instance=~\"$app_instance\", namespace=~\"$namespace\"} or on () vector(0))",
     "legendFormat": "in progress"
    }
   ]
  },
  {
   "title": "Delete Requests Received / Day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(loki_compactor_delete_requests_received_total{app_instance=~\"$app_instance\", namespace=~\"$namespace\"}[1d]))",
     "legendFormat": "received"
    }
   ]
  },
  {
   "title": "Delete Requests Processed / Day",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(loki_compactor_delete_requests_processed_total{app_instance=~\"$app_instance\", namespace=~\"$namespace\"}[1d]))",
     "legendFormat": "processed"
    }
   ]
  },
  { "title": "Compactor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Compactor CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=~\"$namespace\", container=\"compactor\",pod=~\".*loki-compactor.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Compactor memory usage (MiB)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{app_instance=~\"$app_instance\", namespace=~\"$namespace\", pod=~\"(.*compactor.*|.*-backend.*|loki)\"} / 1024 / 1024 ",
     "legendFormat": " {{pod}} "
    }
   ]
  },
  {
   "title": "Compaction run duration (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "loki_boltdb_shipper_compact_tables_operation_duration_seconds{app_instance=~\"$app_instance\", namespace=~\"$namespace\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Deletion metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Failures in Loading Delete Requests / Hour",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(loki_compactor_load_pending_requests_attempts_total{status=\"fail\", app_instance=~\"$app_instance\", namespace=~\"$namespace\"}[1h]))",
     "legendFormat": "failures"
    }
   ]
  },
  {
   "title": "Lines Deleted / Sec",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(loki_compactor_deleted_lines{app_instance=~\"$app_instance\", namespace=~\"$namespace\", container=\"compactor\"}[$__rate_interval])) by (user)",
     "legendFormat": "{{user}}"
    }
   ]
  },
  { "title": "List of deletion requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "In progress/finished",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"$app_instance\", k8s_namespace_name=~\"$namespace\", k8s_container_name=\"compactor\"} |~ \"Started processing delete request|delete request for user marked as processed\" | logfmt | line_format \"{{.ts}} user={{.user}} delete_request_id={{.delete_request_id}} msg={{.msg}}\" "
    }
   ]
  },
  {
   "title": "Requests",
   "type": "logs",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=~\"$app_instance\", k8s_namespace_name=~\"$namespace\", k8s_container_name=\"compactor\"} |~ \"delete request for user added\" | logfmt | line_format \"{{.ts}} user={{.user}} query='{{.query}}'\""
    }
   ]
  }
 ]
}