{
 "title": "Loki / Retention",
 "tags": [ "loki" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "app_instance",
    "label": "app_instance",
    "query": "label_values(loki_build_info, app_instance)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(loki_build_info{app_instance=~\"$app_instance\"}, namespace)"
   },
   { "name": "loki_datasource", "query": "loki" }
  ]
 },
 "panels": [
  { "title": "Resource Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container=\"compactor\", pod=~\"^$app_instance(-.*)?$\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{namespace=~\"$namespace\", container=\"compactor\", pod=~\"^$app_instance(-.*)?$\", resource=\"cpu\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{namespace=~\"$namespace\", container=\"compactor\", resource=\"cpu\", pod=~\"^$app_instance(-.*)?$\"} > 0)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{namespace=~\"$namespace\", container=\"compactor\", pod=~\"^$app_instance(-.*)?$\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{namespace=~\"$namespace\", container=\"compactor\", resource=\"memory\", pod=~\"^$app_instance(-.*)?$\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{namespace=~\"$namespace\", container=\"compactor\", resource=\"memory\", pod=~\"^$app_instance(-.*)?$\"} > 0)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{app_instance=~\"$app_instance\", job=~\"($namespace)/(.*-compactor|.*-backend.*|loki)\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Compaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Last Compact Tables Operation Success",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "loki_boltdb_shipper_compact_tables_operation_last_successful_run_timestamp_seconds{app_instance=~\"$app_instance\", namespace=~\"$namespace\"} * 1e3"
    }
   ]
  },
  {
   "title": "Compact Tables Operations Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "loki_boltdb_shipper_compact_tables_operation_duration_seconds{app_instance=~\"$app_instance\", namespace=~\"$namespace\"}",
     "legendFormat": "duration"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Number of times Tables were skipped during Compaction",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(loki_compactor_locked_table_successive_compaction_skips{app_instance=~\"$app_instance\", namespace=~\"$namespace\"})",
     "legendFormat": "{{table_name}}"
    }
   ]
  },
  {
   "title": "Compact Tables Operations Per Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status)(rate(loki_boltdb_shipper_compact_tables_operation_total{app_instance=~\"$app_instance\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{success}}"
    }
   ]
  },
  { "title": "Retention", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Last Mark Operation Success",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "loki_compactor_apply_retention_last_successful_run_timestamp_seconds{app_instance=~\"$app_instance\", namespace=~\"$namespace\"} * 1e3"
    }
   ]
  },
  {
   "title": "Mark Operations Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "loki_compactor_apply_retention_operation_duration_seconds{app_instance=~\"$app_instance\", namespace=~\"$namespace\"}",
     "legendFormat": "duration"
    }
   ]
  },
  {
   "title": "Mark Operations Per Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status)(rate(loki_compactor_apply_retention_operation_total{app_instance=~\"$app_instance\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{success}}"
    }
   ]
  },
  { "title": "Per Table Marker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Processed Tables Per Action",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by(action)(loki_boltdb_shipper_retention_marker_table_processed_total{app_instance=~\"$app_instance\", namespace=~\"$namespace\"})",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Modified Tables",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by(table,action)(loki_boltdb_shipper_retention_marker_table_processed_total{app_instance=~\"$app_instance\", namespace=~\"$namespace\" , action=~\"modified|deleted\"})",
     "legendFormat": "{{table}}-{{action}}"
    }
   ]
  },
  {
   "title": "Marks Creation Rate Per Table",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (table)(rate(loki_boltdb_shipper_retention_marker_count_total{app_instance=~\"$app_instance\", namespace=~\"$namespace\"}[$__rate_interval])) >0",
     "legendFormat": "{{table}}"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Marked Chunks (24h)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (increase(loki_boltdb_shipper_retention_marker_count_total{app_instance=~\"$app_instance\", namespace=~\"$namespace\"}[24h]))"
    }
   ]
  },
  {
   "title": "Mark Table Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_boltdb_shipper_retention_marker_table_processed_duration_seconds_bucket{app_instance=~\"$app_instance\", namespace=~\"$namespace\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_boltdb_shipper_retention_marker_table_processed_duration_seconds_bucket{app_instance=~\"$app_instance\", namespace=~\"$namespace\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(loki_boltdb_shipper_retention_marker_table_processed_duration_seconds_sum{app_instance=~\"$app_instance\", namespace=~\"$namespace\"}[$__rate_interval])) * 1e3 / sum(rate(loki_boltdb_shipper_retention_marker_table_processed_duration_seconds_count{app_instance=~\"$app_instance\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  { "title": "Sweeper", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Delete Chunks (24h)",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum (increase(loki_boltdb_shipper_retention_sweeper_chunk_deleted_duration_seconds_count{app_instance=~\"$app_instance\", namespace=~\"$namespace\"}[24h]))"
    }
   ]
  },
  {
   "title": "Delete Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_boltdb_shipper_retention_sweeper_chunk_deleted_duration_seconds_bucket{app_instance=~\"$app_instance\", namespace=~\"$namespace\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_boltdb_shipper_retention_sweeper_chunk_deleted_duration_seconds_bucket{app_instance=~\"$app_instance\", namespace=~\"$namespace\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(loki_boltdb_shipper_retention_sweeper_chunk_deleted_duration_seconds_sum{app_instance=~\"$app_instance\", namespace=~\"$namespace\"}[$__rate_interval])) * 1e3 / sum(rate(loki_boltdb_shipper_retention_sweeper_chunk_deleted_duration_seconds_count{app_instance=~\"$app_instance\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Sweeper Lag",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - (loki_boltdb_shipper_retention_sweeper_marker_file_processing_current_time{app_instance=~\"$app_instance\", namespace=~\"$namespace\"} > 0)",
     "legendFormat": "lag"
    }
   ]
  },
  {
   "title": "Marks Files to Process",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(loki_boltdb_shipper_retention_sweeper_marker_files_current{app_instance=~\"$app_instance\", namespace=~\"$namespace\"})",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Delete Rate Per Status",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status)(rate(loki_boltdb_shipper_retention_sweeper_chunk_deleted_duration_seconds_count{app_instance=~\"$app_instance\", namespace=~\"$namespace\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Compactor Logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 65 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"$app_instance\", k8s_namespace_name=\"$namespace\", k8s_container_name=\"compactor\"}"
    }
   ]
  }
 ]
}