{
 "title": "Loki / Operational",
 "tags": [ "loki" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   { "name": "loki_datasource", "query": "loki" },
   {
    "name": "app_instance",
    "label": "app_instance",
    "query": "label_values(loki_build_info, app_instance)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(loki_build_info{app_instance=~\"$app_instance\"}, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Queries/Second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum by (status) (\nlabel_replace(\n  label_replace(\n        rate(loki_request_duration_seconds_count{app_instance=\"$app_instance\", job=~\"($namespace)/(.*-query-frontend|.*-read|loki)\", route=~\"api_prom_query|api_prom_label|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n\"status\", \"${1}\", \"status_code\", \"([a-z]+)\")\n)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Pushes/Second",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "sum by (status) (\nlabel_replace(\n  label_replace(\n          rate(loki_request_duration_seconds_count{app_instance=\"$app_instance\", job=~\"($namespace)/(.*-distributor|.*-write|loki)\", route=~\"api_prom_push|loki_api_v1_push|otlp_v1_logs\"}[$__rate_interval]),\n   \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n\"status\", \"${1}\", \"status_code\", \"([a-z]+)\"))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Lines Per Tenant (top 10)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "topk(10, sum(rate(loki_distributor_lines_received_total{app_instance=\"$app_instance\", namespace=\"$namespace\"}[$__rate_interval])) by (tenant))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "MBs Per Tenant (Top 10)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "targets": [
    {
     "expr": "topk(10, sum(rate(loki_distributor_bytes_received_total{app_instance=\"$app_instance\", namespace=\"$namespace\"}[$__rate_interval])) by (tenant)) / 1024 / 1024",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  {
   "title": "Container Restarts",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 1 },
   "targets": [
    {
     "expr": "increase(kube_pod_container_status_restarts_total{namespace=\"$namespace\", pod=~\"^$app_instance(-.*)?$\"}[10m]) > 0",
     "legendFormat": "{{container}}-{{pod}}"
    }
   ]
  },
  {
   "title": "Push Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/(.*-distributor|.*-write|loki)\", route=~\"api_prom_push|loki_api_v1_push|otlp_v1_logs\", app_instance=~\"$app_instance\"})) * 1e3",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/(.*-distributor|.*-write|loki)\", route=~\"api_prom_push|loki_api_v1_push|otlp_v1_logs\", app_instance=~\"$app_instance\"})) * 1e3",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/(.*-distributor|.*-write|loki)\", route=~\"api_prom_push|loki_api_v1_push|otlp_v1_logs\", app_instance=~\"$app_instance\"})) * 1e3",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Distributor Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (cluster_job:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/(.*-distributor|.*-write|loki)\", app_instance=~\"$app_instance\"})) * 1e3",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (cluster_job:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/(.*-distributor|.*-write|loki)\", app_instance=~\"$app_instance\"})) * 1e3",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (cluster_job:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/(.*-distributor|.*-write|loki)\", app_instance=~\"$app_instance\"})) * 1e3",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Distributor Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(loki_request_duration_seconds_count{app_instance=\"$app_instance\", namespace=\"$namespace\", job=~\"($namespace)/(.*-distributor|.*-write|loki)\", status_code!~\"5[0-9]{2}\"}[$__rate_interval])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{app_instance=\"$app_instance\", namespace=\"$namespace\", job=~\"($namespace)/(.*-distributor|.*-write|loki)\"}[$__rate_interval])) by (route) > 0",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Ingester Latency Write",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\", route=\"/logproto.Pusher/Push\", app_instance=~\"$app_instance\"})) * 1e3",
     "legendFormat": ".99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\", route=\"/logproto.Pusher/Push\", app_instance=~\"$app_instance\"})) * 1e3",
     "legendFormat": ".9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\", route=\"/logproto.Pusher/Push\", app_instance=~\"$app_instance\"})) * 1e3",
     "legendFormat": ".5"
    }
   ]
  },
  {
   "title": "Ingester Success Rate Write",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 11 },
   "targets": [
    {
     "expr": "sum(rate(loki_request_duration_seconds_count{app_instance=\"$app_instance\", namespace=\"$namespace\", job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\", status_code!~\"5[0-9]{2}\", route=\"/logproto.Pusher/Push\"}[$__rate_interval])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{app_instance=\"$app_instance\", namespace=\"$namespace\", job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\", route=\"/logproto.Pusher/Push\"}[$__rate_interval])) by (route) > 0",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Query Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,route) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/(.*-querier|.*-read|loki)\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\", app_instance=\"$app_instance\"}))",
     "legendFormat": "{{route}}-.99"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le,route) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/(.*-querier|.*-read|loki)\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\", app_instance=\"$app_instance\"}))",
     "legendFormat": "{{route}}-.9"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le,route) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/(.*-querier|.*-read|loki)\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\", app_instance=\"$app_instance\"}))",
     "legendFormat": "{{route}}-.5"
    }
   ]
  },
  {
   "title": "Querier Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,route) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/(.*-querier|.*-read|loki)\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\", app_instance=\"$app_instance\"})) * 1e3",
     "legendFormat": ".99-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le,route) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/(.*-querier|.*-read|loki)\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\", app_instance=\"$app_instance\"})) * 1e3",
     "legendFormat": ".9-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le,route) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/(.*-querier|.*-read|loki)\", route=~\"api_prom_query|api_prom_labels|api_prom_label_name_values|loki_api_v1_query|loki_api_v1_query_range|loki_api_v1_label|loki_api_v1_label_name_values\", app_instance=\"$app_instance\"})) * 1e3",
     "legendFormat": ".5-{{route}}"
    }
   ]
  },
  {
   "title": "Querier Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(loki_request_duration_seconds_count{app_instance=\"$app_instance\", namespace=\"$namespace\", job=~\"($namespace)/(.*-querier|.*-read|loki)\", status_code!~\"5[0-9]{2}\"}[$__rate_interval])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{app_instance=\"$app_instance\", namespace=\"$namespace\", job=~\"($namespace)/(.*-querier|.*-read|loki)\"}[$__rate_interval])) by (route) > 0",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Ingester Latency Read",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le,route) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\", route=~\"/logproto.Querier/Query|/logproto.Querier/Label|/logproto.Querier/Series|/logproto.Querier/QuerySample|/logproto.Querier/GetChunkIDs\", app_instance=\"$app_instance\"})) * 1e3",
     "legendFormat": ".99-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by (le,route) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\", route=~\"/logproto.Querier/Query|/logproto.Querier/Label|/logproto.Querier/Series|/logproto.Querier/QuerySample|/logproto.Querier/GetChunkIDs\", app_instance=\"$app_instance\"})) * 1e3",
     "legendFormat": ".9-{{route}}"
    },
    {
     "expr": "histogram_quantile(0.5, sum by (le,route) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\", route=~\"/logproto.Querier/Query|/logproto.Querier/Label|/logproto.Querier/Series|/logproto.Querier/QuerySample|/logproto.Querier/GetChunkIDs\", app_instance=\"$app_instance\"})) * 1e3",
     "legendFormat": ".5-{{route}}"
    }
   ]
  },
  {
   "title": "Ingester Success Rate Read",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 21 },
   "targets": [
    {
     "expr": "sum(rate(loki_request_duration_seconds_count{app_instance=\"$app_instance\", namespace=\"$namespace\", job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\", status_code!~\"5[0-9]{2}\", route=~\"/logproto.Querier/Query|/logproto.Querier/Label|/logproto.Querier/Series|/logproto.Querier/QuerySample|/logproto.Querier/GetChunkIDs\"}[$__rate_interval])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{app_instance=\"$app_instance\", namespace=\"$namespace\", job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\", route=~\"/logproto.Querier/Query|/logproto.Querier/Label|/logproto.Querier/Series|/logproto.Querier/QuerySample|/logproto.Querier/GetChunkIDs\"}[$__rate_interval])) by (route) > 0",
     "legendFormat": "{{route}}"
    }
   ]
  },
  { "title": "Limits", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Discarded Lines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "topk(10,sum by (tenant, reason) (rate(loki_discarded_samples_total{app_instance=\"$app_instance\",namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "{{ tenant }} - {{ reason }}"
    }
   ]
  },
  {
   "title": "Discarded Lines Per Interval",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum by (tenant, reason) (sum_over_time(increase(loki_discarded_samples_total{app_instance=\"$app_instance\",namespace=\"$namespace\"}[$__rate_interval])[$__range:$__rate_interval])))",
     "legendFormat": "{{ tenant }} - {{ reason }}"
    }
   ]
  },
  { "title": "Distributor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container=~\".*distributor.*\", pod=~\"^loki(-.*)?$\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{app_instance=\"$app_instance\", namespace=\"$namespace\", container=~\".*distributor.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Error Log Rate",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({service_name=\"$app_instance\", k8s_namespace_name=\"$namespace\", k8s_container_name=\"distributor\"} | logfmt | level=\"error\"[$__auto]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 40 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"$app_instance\", k8s_namespace_name=\"$namespace\", k8s_container_name=\"distributor\"} | logfmt | level=\"error\""
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "sum(rate(loki_request_duration_seconds_count{app_instance=\"$app_instance\", namespace=\"$namespace\", job=~\"($namespace)/(.*-distributor|.*-write|loki)\", status_code!~\"5[0-9]{2}\"}[$__rate_interval])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{app_instance=\"$app_instance\", namespace=\"$namespace\", job=~\"($namespace)/(.*-distributor|.*-write|loki)\"}[$__rate_interval])) by (route) > 0",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Append Failures By Ingester",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_ingester_append_failures_total{app_instance=\"$app_instance\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Bytes Received/Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_bytes_received_total{app_instance=\"$app_instance\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Lines Received/Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(loki_distributor_lines_received_total{app_instance=\"$app_instance\", namespace=\"$namespace\"}[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Ingester", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 59 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container=~\".*ingester.*\", pod=~\"^loki(-.*)?$\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Error Log Rate",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 18, "x": 6, "y": 59 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({service_name=\"loki\", k8s_namespace_name=\"monitoring\", k8s_container_name=\"ingester\"} | logfmt | level=\"error\"[$__auto]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 18, "x": 6, "y": 62 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"loki\", k8s_namespace_name=\"monitoring\", k8s_container_name=\"ingester\"} | logfmt | level=\"error\""
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{app_instance=\"$app_instance\", namespace=\"$namespace\", container=~\".*ingester.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 73 },
   "targets": [
    {
     "expr": "sum(rate(loki_request_duration_seconds_count{app_instance=\"$app_instance\", namespace=\"$namespace\", job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\", status_code!~\"5[0-9]{2}\"}[$__rate_interval])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{app_instance=\"$app_instance\", namespace=\"$namespace\", job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\"}[$__rate_interval])) by (route) > 0",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Streams",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 80 },
   "collapsed": true,
   "panels": [
    {
     "title": "Active Streams",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 81 },
     "targets": [
      {
       "expr": "topk(10,sum by (tenant) (loki_ingester_memory_streams{app_instance=\"$app_instance\",job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\"}))",
       "legendFormat": "{{ tenant }}"
      }
     ]
    },
    {
     "title": "Streams Created/Sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 81 },
     "targets": [
      {
       "expr": "topk(10, sum by (tenant) (rate(loki_ingester_streams_created_total{app_instance=\"$app_instance\",job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\"}[$__rate_interval]) > 0))",
       "legendFormat": "{{ tenant }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Chunks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "Chunks Flushed/Sec",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "targets": [
      {
       "expr": "sum(rate(loki_ingester_chunks_flushed_total{app_instance=\"$app_instance\",job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\"}[$__rate_interval]))",
       "legendFormat": "Chunks"
      },
      {
       "expr": "sum(increase(loki_chunk_store_deduped_chunks_total{app_instance=\"$app_instance\", job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\"}[$__rate_interval]))/sum(increase(loki_ingester_chunks_flushed_total{app_instance=\"$app_instance\", job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\"}[$__rate_interval])) < 1",
       "legendFormat": "De-Dupe Ratio"
      }
     ]
    },
    {
     "title": "Chunk Size Bytes",
     "type": "heatmap",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "targets": [
      {
       "expr": "sum(rate(loki_ingester_chunk_size_bytes_bucket{app_instance=\"$app_instance\",job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\"}[$__rate_interval])) by (le)",
       "legendFormat": "{{ le }}"
      }
     ]
    },
    {
     "title": "Chunk Flush Reason %",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 98 },
     "targets": [
      {
       "expr": "sum by(reason) (rate(loki_ingester_chunks_flushed_total{app_instance=~\"$app_instance\",job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\", namespace=~\"$namespace\"}[$__rate_interval])) / ignoring(reason) group_left sum(rate(loki_ingester_chunks_flushed_total{app_instance=~\"$app_instance\",job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\", namespace=~\"$namespace\"}[$__rate_interval]))",
       "legendFormat": "{{ reason }}"
      }
     ]
    },
    {
     "title": "Chunk Utilization",
     "type": "heatmap",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 98 },
     "targets": [
      {
       "expr": "sum by (le) (rate(loki_ingester_chunk_utilization_bucket{app_instance=\"$app_instance\", job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\"}[$__rate_interval]))",
       "legendFormat": "{{ le }}"
      }
     ]
    }
   ]
  },
  { "title": "Querier", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 82 } },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 83 },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container=~\".*querier.*\", pod=~\"^loki(-.*)?$\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Error Log Rate",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 18, "x": 6, "y": 83 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({service_name=\"loki\", k8s_namespace_name=\"monitoring\", k8s_container_name=~\"querier|query-frontend|query-scheduler|index-gateway\"} | logfmt |  level=\"error\"[$__auto]))"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 18, "w": 18, "x": 6, "y": 86 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"loki\", k8s_namespace_name=\"monitoring\", k8s_container_name=~\"querier|query-frontend|query-scheduler|index-gateway\"} | logfmt | level=\"error\""
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "go_memstats_heap_inuse_bytes{app_instance=\"$app_instance\", namespace=\"$namespace\", container=~\".*querier.*\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "sum(rate(loki_request_duration_seconds_count{app_instance=\"$app_instance\", namespace=\"$namespace\", job=~\"($namespace)/(.*-querier|.*-read|loki)\", status_code!~\"5[0-9]{2}\"}[$__rate_interval])) by (route)\n/\nsum(rate(loki_request_duration_seconds_count{app_instance=\"$app_instance\", namespace=\"$namespace\", job=~\"($namespace)/(.*-querier|.*-read|loki)\"}[$__rate_interval])) by (route) > 0",
     "legendFormat": "{{route}}"
    }
   ]
  }
 ]
}