{
 "title": "Loki / Writes",
 "tags": [ "loki" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "app_instance",
    "label": "app_instance",
    "query": "label_values(loki_build_info, app_instance)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(loki_build_info{app_instance=~\"$app_instance\"}, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Distributor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(loki_request_duration_seconds_count{app_instance=~\"$app_instance\",job=~\"($namespace)/(.*-distributor|.*-write|loki)\", route=~\"api_prom_push|loki_api_v1_push|otlp_v1_logs|/httpgrpc.HTTP/Handle\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"status_code\", \"([a-zA-Z]+)\"))\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{app_instance=~\"$app_instance\", job=~\"($namespace)/(.*-distributor|.*-write|loki)\", route=~\"api_prom_push|loki_api_v1_push|otlp_v1_logs|/httpgrpc.HTTP/Handle\"})) * 1e3",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{app_instance=~\"$app_instance\", job=~\"($namespace)/(.*-distributor|.*-write|loki)\", route=~\"api_prom_push|loki_api_v1_push|otlp_v1_logs|/httpgrpc.HTTP/Handle\"})) * 1e3",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "1e3 * sum(cluster_job_route:loki_request_duration_seconds_sum:sum_rate{app_instance=~\"$app_instance\", job=~\"($namespace)/(.*-distributor|.*-write|loki)\", route=~\"api_prom_push|loki_api_v1_push|otlp_v1_logs|/httpgrpc.HTTP/Handle\"}) / sum(cluster_job_route:loki_request_duration_seconds_count:sum_rate{app_instance=~\"$app_instance\", job=~\"($namespace)/(.*-distributor|.*-write|loki)\", route=~\"api_prom_push|loki_api_v1_push|otlp_v1_logs|/httpgrpc.HTTP/Handle\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Per Pod Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_request_duration_seconds_bucket{app_instance=~\"$app_instance\", job=~\"($namespace)/(.*-distributor|.*-write|loki)\", route=~\"api_prom_push|loki_api_v1_push|otlp_v1_logs|/httpgrpc.HTTP/Handle\"}[$__rate_interval])) by (le,pod)) * 1e3",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Distributor - Structured Metadata",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 }
  },
  {
   "title": "Per Total Received Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum (rate(loki_distributor_structured_metadata_bytes_received_total{app_instance=~\"$app_instance\",job=~\"($namespace)/(.*-distributor|.*-write|loki)\",}[$__rate_interval])) / sum(rate(loki_distributor_bytes_received_total{app_instance=~\"$app_instance\",job=~\"($namespace)/(.*-distributor|.*-write|loki)\",}[$__rate_interval]))",
     "legendFormat": "bytes"
    }
   ]
  },
  {
   "title": "Per Tenant",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (tenant) (rate(loki_distributor_structured_metadata_bytes_received_total{app_instance=~\"$app_instance\",job=~\"($namespace)/(.*-distributor|.*-write|loki)\",}[$__rate_interval])) / ignoring(tenant) group_left sum(rate(loki_distributor_structured_metadata_bytes_received_total{app_instance=~\"$app_instance\",job=~\"($namespace)/(.*-distributor|.*-write|loki)\",}[$__rate_interval]))",
     "legendFormat": "{{tenant}}"
    }
   ]
  },
  { "title": "Ingester - Zone Aware", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(loki_request_duration_seconds_count{app_instance=~\"$app_instance\",job=~\"($namespace)/(.*-partition-ingester|.*-ingester|.*-write|loki)\", route=\"/logproto.Pusher/Push\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"status_code\", \"([a-zA-Z]+)\"))\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{app_instance=~\"$app_instance\", job=~\"($namespace)/(.*-partition-ingester|.*-ingester|.*-write|loki)\", route=\"/logproto.Pusher/Push\"})) * 1e3",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{app_instance=~\"$app_instance\", job=~\"($namespace)/(.*-partition-ingester|.*-ingester|.*-write|loki)\", route=\"/logproto.Pusher/Push\"})) * 1e3",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "1e3 * sum(cluster_job_route:loki_request_duration_seconds_sum:sum_rate{app_instance=~\"$app_instance\", job=~\"($namespace)/(.*-partition-ingester|.*-ingester|.*-write|loki)\", route=\"/logproto.Pusher/Push\"}) / sum(cluster_job_route:loki_request_duration_seconds_count:sum_rate{app_instance=~\"$app_instance\", job=~\"($namespace)/(.*-partition-ingester|.*-ingester|.*-write|loki)\", route=\"/logproto.Pusher/Push\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Per Pod Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_request_duration_seconds_bucket{app_instance=~\"$app_instance\", job=~\"($namespace)/(.*-partition-ingester|.*-ingester|.*-write|loki)\", route=\"/logproto.Pusher/Push\"}[$__rate_interval])) by (le,pod)) * 1e3",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Ingester", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(loki_request_duration_seconds_count{app_instance=~\"$app_instance\",job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\", route=\"/logproto.Pusher/Push\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"status_code\", \"([a-zA-Z]+)\"))\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{app_instance=~\"$app_instance\", job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\", route=\"/logproto.Pusher/Push\"})) * 1e3",
     "legendFormat": "99th percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (cluster_job_route:loki_request_duration_seconds_bucket:sum_rate{app_instance=~\"$app_instance\", job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\", route=\"/logproto.Pusher/Push\"})) * 1e3",
     "legendFormat": "50th percentile"
    },
    {
     "expr": "1e3 * sum(cluster_job_route:loki_request_duration_seconds_sum:sum_rate{app_instance=~\"$app_instance\", job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\", route=\"/logproto.Pusher/Push\"}) / sum(cluster_job_route:loki_request_duration_seconds_count:sum_rate{app_instance=~\"$app_instance\", job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\", route=\"/logproto.Pusher/Push\"})",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Per Pod Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_request_duration_seconds_bucket{app_instance=~\"$app_instance\", job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\", route=\"/logproto.Pusher/Push\"}[$__rate_interval])) by (le,pod)) * 1e3",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Index", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(loki_index_request_duration_seconds_count{app_instance=~\"$app_instance\",job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\", operation=\"index_chunk\"}[$__rate_interval]),\n  \"status\", \"${1}xx\", \"status_code\", \"([0-9])..\"),\n  \"status\", \"${1}\", \"status_code\", \"([a-zA-Z]+)\"))\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_index_request_duration_seconds_bucket{app_instance=~\"$app_instance\",job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\", operation=\"index_chunk\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "99th Percentile"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(loki_index_request_duration_seconds_bucket{app_instance=~\"$app_instance\",job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\", operation=\"index_chunk\"}[$__rate_interval])) by (le)) * 1e3",
     "legendFormat": "50th Percentile"
    },
    {
     "expr": "sum(rate(loki_index_request_duration_seconds_sum{app_instance=~\"$app_instance\",job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\", operation=\"index_chunk\"}[$__rate_interval])) * 1e3 / sum(rate(loki_index_request_duration_seconds_count{app_instance=~\"$app_instance\",job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\", operation=\"index_chunk\"}[$__rate_interval]))",
     "legendFormat": "Average"
    }
   ]
  },
  {
   "title": "Per Pod Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(loki_index_request_duration_seconds_bucket{app_instance=~\"$app_instance\",job=~\"($namespace)/(.*-partition-ingester.*|.*-ingester.*|.*-write|loki)\", operation=\"index_chunk\"}[$__rate_interval])) by (le,pod)) * 1e3",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}