{
 "title": "Loki / Logs",
 "tags": [ "loki" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "app_instance",
    "label": "app_instance",
    "query": "label_values(loki_build_info, app_instance)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(loki_build_info{app_instance=~\"$app_instance\"}, namespace)"
   },
   { "name": "loki_datasource", "query": "loki" },
   {
    "name": "container",
    "query": {
     "query": "label_values(loki_build_info{app_instance=\"$app_instance\", namespace=\"$namespace\"},container)"
    }
   },
   { "name": "level", "query": "debug,info,warn,error" },
   { "name": "filter", "label": "LogQL Filter" }
  ]
 },
 "panels": [
  {
   "title": "goroutines",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by (pod)(go_goroutines{app_instance=\"$app_instance\", namespace=\"$namespace\", container=~\"$container\"  })"
    }
   ]
  },
  {
   "title": "gc duration",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(go_gc_duration_seconds{app_instance=\"$app_instance\", namespace=\"$namespace\", container=~\"$container\"}) by (quantile)",
     "legendFormat": "{{quantile}}"
    }
   ]
  },
  {
   "title": "tx",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_network_transmit_bytes_total{namespace=\"$namespace\", pod=~\"^$app_instance-$container(-.*)?$\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "rx",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_network_receive_bytes_total{namespace=\"$namespace\", pod=~\"^$app_instance-$container(-.*)?$\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "cpu",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_cpu_usage_seconds_total{namespace=\"$namespace\", container=~\"$container\", pod=~\"^$app_instance(-.*)?$\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "working set",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (pod)(container_memory_working_set_bytes{namespace=\"$namespace\", container=~\"$container\", pod=~\"^$app_instance(-.*)?$\"})"
    }
   ]
  },
  {
   "title": "restarts",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{namespace=\"$namespace\", container=~\"$container\", pod=~\"^$app_instance(-.*)?$\"} > 0",
     "legendFormat": "{{reason}}"
    }
   ]
  },
  {
   "title": "Log Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(rate({service_name=\"$app_instance\", k8s_namespace_name=\"$namespace\", k8s_container_name=~\"$container\" } |logfmt| level=~\"$level\" |= \"$filter\" | __error__=\"\" [$__auto])) by (level)",
     "legendFormat": "{{level}}"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{service_name=\"$app_instance\", k8s_namespace_name=\"$namespace\", k8s_container_name=~\"$container\"} | logfmt | level=~\"$level\" |= \"$filter\""
    }
   ]
  }
 ]
}