{
 "title": "ArgoCD Audit",
 "tags": [
  "argocd",
  "iberdrola"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {}
   },
   { "name": "filter" }
  ]
 },
 "panels": [
  {
   "title": "ArgoCD Server logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{k8s_cluster_name=~\"$cluster\", k8s_container_name=\"server\"} |= `` | label_format level=detected_level |= \"$filter\""
    }
   ]
  },
  { "title": "ArgoCD Syncs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "ArgoCD \"argocd\" syncs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 19, "x": 0, "y": 11 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (user,dest_namespace,application) (\r\n  count_over_time(\r\n    {k8s_cluster_name=~\"$cluster\", k8s_container_name=\"server\"} |= `` | label_format level=detected_level | json | user=\"argocd\", msg =~ `.*initiated sync.*` |= \"$filter\"\r\n    [$__auto]\r\n  )\r\n) ",
     "legendFormat": "{{user}}/{{dest_namespace}}/{{application}}"
    }
   ]
  },
  {
   "title": "ArgoCD syncs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\r\n  count_over_time(\r\n  {k8s_cluster_name=~\"$cluster\", k8s_container_name=\"server\"}\r\n    |= `` \r\n    | label_format level=detected_level \r\n    | json \r\n    | user=\"argocd\", application!=\"\", msg =~ `.*initiated sync.*`\r\n    |= \"$filter\"\r\n  [$__auto]\r\n  )\r\n)",
     "legendFormat": "Total"
    },
    {
     "direction": "backward",
     "expr": "sum(\r\n  count_over_time(\r\n  {k8s_cluster_name=~\"$cluster\", k8s_container_name=\"server\"}\r\n    |= `` \r\n    | label_format level=detected_level \r\n    | json \r\n    | user=\"argocd\", application=~\".*-aks-.*\", msg =~ `.*initiated sync.*`\r\n    |= \"$filter\"\r\n  [$__auto]\r\n  )\r\n)",
     "legendFormat": "AKS"
    },
    {
     "direction": "backward",
     "expr": "sum(\r\n  count_over_time(\r\n  {k8s_cluster_name=~\"$cluster\", k8s_container_name=\"server\"}\r\n    |= `` \r\n    | label_format level=detected_level \r\n    | json \r\n    | user=\"argocd\", application=~\".*-eks-.*\", msg =~ `.*initiated sync.*`\r\n    |= \"$filter\"\r\n  [$__auto]\r\n  )\r\n)",
     "legendFormat": "EKS"
    },
    {
     "direction": "backward",
     "expr": "sum(\r\n  count_over_time(\r\n  {k8s_cluster_name=~\"$cluster\", k8s_container_name=\"server\"}\r\n    |= `` \r\n    | label_format level=detected_level \r\n    | json \r\n    | user=\"argocd\", application=~\".*-ocp-.*\", msg =~ `.*initiated sync.*`\r\n    |= \"$filter\"\r\n  [$__auto]\r\n  )\r\n)",
     "legendFormat": "OCP"
    }
   ]
  },
  {
   "title": "ArgoCD \"human\" syncs",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (user,dest_namespace,application) (\r\n  count_over_time(\r\n    {k8s_cluster_name=~\"$cluster\", k8s_container_name=\"server\"} |= `` | label_format level=detected_level | json | user!=\"argocd\", msg =~ `.*initiated sync.*` |= \"$filter\"\r\n    [$__auto]\r\n  )\r\n) ",
     "legendFormat": "{{user}}/{{dest_namespace}}/{{application}}"
    }
   ]
  },
  {
   "title": "ArgoCD \"human\" partial syncs",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (user,dest_namespace,application) (\r\n  count_over_time(\r\n    {k8s_cluster_name=~\"$cluster\", k8s_container_name=\"server\"} |= `` | label_format level=detected_level | json | user!=\"argocd\", msg =~ `.*initiated partial sync.*` |= \"$filter\"\r\n    [$__auto]\r\n  )\r\n) ",
     "legendFormat": "{{user}}/{{dest_namespace}}/{{application}}"
    }
   ]
  },
  {
   "title": "Human syncs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\r\n  count_over_time(\r\n  {k8s_cluster_name=~\"$cluster\", k8s_container_name=\"server\"}\r\n    |= `` \r\n    | label_format level=detected_level \r\n    | json \r\n    | user!=\"argocd\", application!=\"\", msg =~ `.*initiated sync.*`\r\n    |= \"$filter\"\r\n  [$__auto]\r\n  )\r\n)",
     "legendFormat": "Total"
    },
    {
     "direction": "backward",
     "expr": "sum(\r\n  count_over_time(\r\n  {k8s_cluster_name=~\"$cluster\", k8s_container_name=\"server\"}\r\n    |= `` \r\n    | label_format level=detected_level \r\n    | json \r\n    | user!=\"argocd\", application=~\".*-aks-.*\", msg =~ `.*initiated sync.*`\r\n    |= \"$filter\"\r\n  [$__auto]\r\n  )\r\n)",
     "legendFormat": "AKS"
    },
    {
     "direction": "backward",
     "expr": "sum(\r\n  count_over_time(\r\n  {k8s_cluster_name=~\"$cluster\", k8s_container_name=\"server\"}\r\n    |= `` \r\n    | label_format level=detected_level \r\n    | json \r\n    | user!=\"argocd\", application=~\".*-eks-.*\", msg =~ `.*initiated sync.*`\r\n    |= \"$filter\"\r\n  [$__auto]\r\n  )\r\n)",
     "legendFormat": "EKS"
    },
    {
     "direction": "backward",
     "expr": "sum(\r\n  count_over_time(\r\n  {k8s_cluster_name=~\"$cluster\", k8s_container_name=\"server\"}\r\n    |= `` \r\n    | label_format level=detected_level \r\n    | json \r\n    | user!=\"argocd\", application=~\".*-ocp-.*\", msg =~ `.*initiated sync.*`\r\n    |= \"$filter\"\r\n  [$__auto]\r\n  )\r\n)",
     "legendFormat": "OCP"
    }
   ]
  },
  {
   "title": "Human partial syncs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\r\n  count_over_time(\r\n  {k8s_cluster_name=~\"$cluster\", k8s_container_name=\"server\"}\r\n    |= `` \r\n    | label_format level=detected_level \r\n    | json \r\n    | user!=\"argocd\", application!=\"\", msg =~ `.*initiated partial sync.*`\r\n    |= \"$filter\"\r\n  [$__auto]\r\n  )\r\n)",
     "legendFormat": "Total"
    },
    {
     "direction": "backward",
     "expr": "sum(\r\n  count_over_time(\r\n  {k8s_cluster_name=~\"$cluster\", k8s_container_name=\"server\"}\r\n    |= `` \r\n    | label_format level=detected_level \r\n    | json \r\n    | user!=\"argocd\", application=~\".*-aks-.*\", msg =~ `.*initiated partial sync.*`\r\n    |= \"$filter\"\r\n  [$__auto]\r\n  )\r\n)",
     "legendFormat": "AKS"
    },
    {
     "direction": "backward",
     "expr": "sum(\r\n  count_over_time(\r\n  {k8s_cluster_name=~\"$cluster\", k8s_container_name=\"server\"}\r\n    |= `` \r\n    | label_format level=detected_level \r\n    | json \r\n    | user!=\"argocd\", application=~\".*-eks-.*\", msg =~ `.*initiated partial sync.*`\r\n    |= \"$filter\"\r\n  [$__auto]\r\n  )\r\n)",
     "legendFormat": "EKS"
    },
    {
     "direction": "backward",
     "expr": "sum(\r\n  count_over_time(\r\n  {k8s_cluster_name=~\"$cluster\", k8s_container_name=\"server\"}\r\n    |= `` \r\n    | label_format level=detected_level \r\n    | json \r\n    | user!=\"argocd\", application=~\".*-ocp-.*\", msg =~ `.*initiated partial sync.*`\r\n    |= \"$filter\"\r\n  [$__auto]\r\n  )\r\n)",
     "legendFormat": "OCP"
    }
   ]
  },
  { "title": "User activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Total users",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(\r\n  count by (email) (\r\n    count_over_time(\r\n      {k8s_cluster_name=~\"$cluster\", k8s_container_name=\"server\"}\r\n      | json\r\n      | line_format \"{{.grpc_request_claims}}\"\r\n      | json\r\n      | email!=\"\"\r\n      |= \"$filter\"\r\n      [1m]\r\n    )\r\n  )\r\n)",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "User activity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (email) (\r\n  count_over_time(\r\n\t\t{k8s_cluster_name=~\"$cluster\", k8s_container_name=\"server\"} | json | line_format \"{{.grpc_request_claims}}\" | json | email!=\"\" |= \"$filter\"\r\n    [$__auto]\r\n  )\r\n)",
     "legendFormat": "{{email}}"
    }
   ]
  },
  {
   "title": "User activity by company",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\r\n  count_over_time(\r\n    {k8s_cluster_name=~\"$cluster\", k8s_container_name=\"server\"}\r\n    | json\r\n    | line_format \"{{.grpc_request_claims}}\"\r\n    | json\r\n    | email=~\".*iberdrola.*\"\r\n    |= \"$filter\"\r\n    [$__auto]\r\n  )\r\n)",
     "legendFormat": "Iberdrola"
    },
    {
     "direction": "backward",
     "expr": "sum(\r\n  count_over_time(\r\n    {k8s_cluster_name=~\"$cluster\", k8s_container_name=\"server\"}\r\n    | json\r\n    | line_format \"{{.grpc_request_claims}}\"\r\n    | json\r\n    | email=~\".*scottishpower.*\"\r\n    |= \"$filter\"\r\n    [$__auto]\r\n  )\r\n)",
     "legendFormat": "Scottish Power"
    }
   ]
  },
  {
   "title": "User activity by application",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (grpc_request_content_name) (\r\n  count_over_time(\r\n\t\t{k8s_cluster_name=~\"$cluster\", k8s_container_name=\"server\"} | json | line_format \"{{.grpc_request_claims}}\" | json | grpc_request_content_name!=\"\" |=\"$filter\"\r\n    [$__auto]\r\n  )\r\n)",
     "legendFormat": "{{email}}"
    }
   ]
  },
  {
   "title": "User activity by action",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (msg) (\r\n  count_over_time(\r\n\t\t{k8s_cluster_name=~\"$cluster\", k8s_container_name=\"server\"} | json | msg!=\"\" | msg!~\".*TotalAlloc.*\" | msg!~\".*argocd-notifications.*\" |= \"$filter\"\r\n    [$__auto]\r\n  )\r\n)",
     "legendFormat": "{{email}}"
    }
   ]
  },
  { "title": "Cluster deletions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "Cluster deletion activity (by user)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 48 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (email, cluster) (\r\n  count_over_time(\r\n    {k8s_cluster_name=~\"$cluster\", k8s_container_name=\"server\"}\r\n    | json\r\n    | msg=\"received unary call /cluster.ClusterService/Delete\"\r\n    | label_format cluster=\"{{.grpc_request_content_id_value}}\"\r\n    | line_format \"{{.grpc_request_claims}}\"\r\n    | json\r\n    | email!=\"\"\r\n    [$__auto]\r\n  )\r\n)",
     "legendFormat": "{{cluster}} deleted by {{email}}"
    }
   ]
  },
  {
   "title": "Cluster deletion activity (by Service Account)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (sub, cluster) (\r\n  count_over_time(\r\n    {k8s_cluster_name=~\"$cluster\", k8s_container_name=\"server\"}\r\n    | json\r\n    | msg=\"received unary call /cluster.ClusterService/Delete\"\r\n    | grpc_request_content_name!=\"\"\r\n    | label_format cluster=\"{{.grpc_request_content_name}}\"\r\n    | line_format \"{{.grpc_request_claims}}\"\r\n    | json\r\n    | sub!=\"\"\r\n    [$__auto]\r\n  )\r\n)",
     "legendFormat": "{{cluster}} deleted by {{sub}}"
    }
   ]
  }
 ]
}