{
 "title": "Istio Logs",
 "tags": [
  "iberdrola",
  "istio",
  "ingress",
  "k8s"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {}
   },
   {
    "name": "ingress",
    "label": "ingress",
    "query": {}
   },
   { "name": "filter", "label": "filter" }
  ]
 },
 "panels": [
  {
   "title": "Logs number",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\r\n  count_over_time(\r\n    {k8s_cluster_name=~\"$cluster\", service_name=~\"$ingress\"}\r\n    |~ \"$filter\"\r\n    [$__range]\r\n  )\r\n)"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "logs",
   "description": "To search more than one word:\n| -> OR\n",
   "gridPos": { "h": 8, "w": 22, "x": 2, "y": 0 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{k8s_cluster_name=~\"$cluster\", service_name=~\"$ingress\"} |~ \"$filter\""
    }
   ]
  },
  {
   "title": "Request authority",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (authority) (\r\n  count_over_time(\r\n    {k8s_cluster_name=~\"$cluster\", service_name=~\"$ingress\"}\r\n    | json\r\n    | authority != \"\"\r\n    |~ \"$filter\"\r\n    [$__auto]\r\n  )\r\n)",
     "legendFormat": "{{authority}}"
    }
   ]
  },
  {
   "title": "Request return Code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (response_code) (\r\n  count_over_time(\r\n    {k8s_cluster_name=~\"$cluster\", service_name=~\"$ingress\"}\r\n    | json\r\n    | response_code != \"\"\r\n    |~ \"$filter\"\r\n    [$__auto]\r\n  )\r\n)",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "Request method",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (method) (\r\n  count_over_time(\r\n    {k8s_cluster_name=~\"$cluster\", service_name=~\"$ingress\"}\r\n    | json\r\n    | method != \"\"\r\n    |~ \"$filter\"\r\n    [$__auto]\r\n  )\r\n)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Request route name",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (route_name,route_short) (\r\n  count_over_time(\r\n    {k8s_cluster_name=~\"$cluster\", service_name=~\"$ingress\"}\r\n    | json\r\n    | route_name != \"\"\r\n    | label_format route_short=`{{ regexReplaceAll \".*\\\\.([^.]+)\\\\.[^.]+$\" .route_name \"${1}\" }}`\r\n    |~ \"$filter\"\r\n    [$__auto]\r\n  )\r\n)",
     "legendFormat": "{{route_name}}({{route_short}})"
    }
   ]
  },
  {
   "title": "Request user agent",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (user_agent) (\r\n  count_over_time(\r\n    {k8s_cluster_name=~\"$cluster\", service_name=~\"$ingress\"}\r\n    | json\r\n    | user_agent != \"\"\r\n    |~ \"$filter\"\r\n    [$__auto]\r\n  )\r\n)",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Request upstream_host (destination pod IP)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (upstream_host) (\r\n  count_over_time(\r\n    {k8s_cluster_name=~\"$cluster\", service_name=~\"$ingress\"}\r\n    | json\r\n    | upstream_host != \"\"\r\n    |~ \"$filter\"\r\n    [$__auto]\r\n  )\r\n)",
     "legendFormat": "{{response_code}}"
    }
   ]
  },
  {
   "title": "Request path",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (path) (\r\n  count_over_time(\r\n    {k8s_cluster_name=~\"$cluster\", service_name=~\"$ingress\"}\r\n    | json\r\n    | path != \"\"\r\n    |~ \"$filter\"\r\n    [$__auto]\r\n  )\r\n)",
     "legendFormat": "{{method}}"
    }
   ]
  }
 ]
}