{
 "title": "ArgoCD Table",
 "description": "Official ArgoCD Dashboard as of June 2021",
 "tags": [
  "argocd",
  "iberdrola"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "argocd_instance",
    "query": {
     "query": "label_values({cluster=~\"aks-kpescorpostarg-dev|aks-kpescorpostarg-pre|aks-kpescorpostarg-pro|aks-kpescorpostarl-dev|aks-kpesitmstarg-pro\"},cluster)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(argocd_cluster_info{cluster=~\"$argocd_instance\"},server)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(\n  (max by (server) (\n    argocd_cluster_connection_status{\n      cluster=~\"$argocd_instance\",\n      server=~\"$cluster\"\n    }\n  )) > 0\n)",
     "legendFormat": "Total of clusters"
    }
   ]
  },
  {
   "title": "Infrastructure",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (name) (argocd_cluster_info{cluster=~\"$argocd_instance\", name=~\".*eks.*\"}== 1))",
     "legendFormat": "EKS clusters"
    },
    {
     "expr": "count(count by (name) (argocd_cluster_info{cluster=~\"$argocd_instance\", name=~\".*aks.*\"}== 1))",
     "legendFormat": "AKS clusters"
    },
    {
     "expr": "count(count by (name) (argocd_cluster_info{cluster=~\"$argocd_instance\", name=~\".*ocp.*\"}== 1))",
     "legendFormat": "OCP clusters"
    }
   ]
  },
  {
   "title": "Environments",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (name) (argocd_cluster_info{cluster=~\"$argocd_instance\", name=~\".*-cdv.*\"}== 1))",
     "legendFormat": "CDV"
    },
    {
     "expr": "count(count by (name) (argocd_cluster_info{cluster=~\"$argocd_instance\", name=~\".*-dev.*\"}== 1))",
     "legendFormat": "DEV"
    },
    {
     "expr": "count(count by (name) (argocd_cluster_info{cluster=~\"$argocd_instance\", name=~\".*-int.*\"}== 1))",
     "legendFormat": "INT"
    },
    {
     "expr": "count(count by (name) (argocd_cluster_info{cluster=~\"$argocd_instance\", name=~\".*-pre.*\"}== 1))",
     "legendFormat": "PRE"
    },
    {
     "expr": "count(count by (name) (argocd_cluster_info{cluster=~\"$argocd_instance\", name=~\".*-pro.*\"}== 1))",
     "legendFormat": "PRO"
    }
   ]
  },
  {
   "title": "Cluster type",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (name) (argocd_cluster_info{cluster=~\"$argocd_instance\", name=~\".*op.*\"}== 1))",
     "legendFormat": "OP Clusters"
    },
    {
     "expr": "count(count by (name) (argocd_cluster_info{cluster=~\"$argocd_instance\", name=~\".*(kp|4p).*\"}== 1))",
     "legendFormat": "Package Clusters"
    },
    {
     "expr": "count(count by (name) (argocd_cluster_info{cluster=~\"$argocd_instance\", name=~\".*ocp.*\"}== 1))",
     "legendFormat": "OCP Clusters"
    }
   ]
  },
  {
   "title": "K8S versions",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (k8s_version) (argocd_cluster_info{cluster=~\"$argocd_instance\"})",
     "legendFormat": "{{k8s_version}}"
    }
   ]
  },
  {
   "title": "Company",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (name) (argocd_cluster_info{cluster=~\"$argocd_instance\", name=~\".*(es|-ib-|-ibe-|).*\"}== 1))",
     "legendFormat": "Iberdrola"
    },
    {
     "expr": "count(count by (name) (argocd_cluster_info{cluster=~\"$argocd_instance\", name=~\".*(uk|-sp-|-spw-).*\"}== 1))",
     "legendFormat": "Scottish Power"
    },
    {
     "expr": "count(count by (name) (argocd_cluster_info{cluster=~\"$argocd_instance\", name=~\".*(-ne-).*\"}== 1))",
     "legendFormat": "Neoenergia"
    }
   ]
  },
  { "title": "Clusters list", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Total managed clusters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\r\n  max by (server) (\r\n    argocd_cluster_connection_status{\r\n      cluster=~\"$argocd_instance\",\r\n      server=~\"$cluster\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Connected clusters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  (max by (server) (\r\n    argocd_cluster_connection_status{\r\n      cluster=~\"$argocd_instance\",\r\n      server=~\"$cluster\"\r\n    }\r\n  )) > 0\r\n)",
     "legendFormat": "Connected"
    }
   ]
  },
  {
   "title": "Disconnected clusters",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((1 - max by (server) (argocd_cluster_connection_status{cluster=~\"$argocd_instance\", server=~\"$cluster\"})) > 0)",
     "legendFormat": "Disconnected"
    }
   ]
  },
  {
   "title": "Managed cluster health",
   "type": "state-timeline",
   "gridPos": { "h": 25, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "max by (server, name) (\r\n  argocd_cluster_connection_status{cluster=~\"$argocd_instance\", server=~\"$cluster\"}\r\n  * on (cluster, server) group_left(name)\r\n  argocd_cluster_info{cluster=~\"$argocd_instance\", server=~\"$cluster\"}\r\n)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "ArgoCD Child Clusters List",
   "type": "table",
   "gridPos": { "h": 18, "w": 24, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "max by (server) (argocd_cluster_connection_status{cluster=~\"$argocd_instance\", server=~\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "group by (server, name, k8s_version) (argocd_cluster_info{cluster=~\"$argocd_instance\", server=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}