{
 "title": "ArgoCD Health (in progress)",
 "description": "This dashboard provides a resource usage overview of the ArgoCD components.\n\nIt includes CPU and Memory requests, limits and usage. In addition, the last termination reason is plotted and the cache hit ratio is available.",
 "tags": [
  "argocd",
  "iberdrola"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_pod_info,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "![argoimage](https://icon.icepanel.io/Technology/svg/Argo-CD.svg)"
   }
  },
  {
   "title": "Number of Pods",
   "type": "stat",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sort_desc(\r\n  sum by (component) (\r\n    label_replace(\r\n      kube_pod_info{\r\n        cluster=\"$cluster\",\r\n        pod=~\"argocd-(application-controller|applicationset-controller|dex-server|notifications|redis-ha-haproxy|redis-ha-server|repo-server|server).*\",\r\n        container!=\"\"\r\n      },\r\n      \"component\", \"$1\", \"pod\",\r\n      \"argocd-(application-controller|applicationset-controller|dex-server|notifications|redis-ha-haproxy|redis-ha-server|repo-server|server).*\"\r\n    )\r\n  )\r\n)",
     "legendFormat": "{{app_kubernetes_io_component}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(argocd_info{cluster=\"$cluster\"}) by (version)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "ArgoCD / application-controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 }
  },
  {
   "title": "CPU Core Usage vs. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      cluster=\"$cluster\",\r\n      resource=\"cpu\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-application-controller.*\"\r\n    }\r\n  )\r\n)",
     "legendFormat": "limit"
    },
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      cluster=\"$cluster\",\r\n      resource=\"cpu\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-application-controller.*\"\r\n    }\r\n  )\r\n)",
     "legendFormat": "request"
    },
    {
     "expr": "max by (pod) (\r\n  irate(container_cpu_usage_seconds_total{cluster=\"$cluster\", container=\"application-controller\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\r\n  max by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      cluster=\"$cluster\",\r\n      resource=\"memory\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-application-controller.*\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "limit"
    },
    {
     "expr": "max(\r\n  max by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      cluster=\"$cluster\",\r\n      resource=\"memory\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-application-controller.*\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "request"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{cluster=\"$cluster\",container=\"application-controller\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\r\nkube_pod_container_status_last_terminated_reason{\r\n  cluster=\"$cluster\",\r\n  pod=~\"application-controller.*\"\r\n} != 0\r\n",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  {
   "title": "ArgoCD / applicationset-controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 }
  },
  {
   "title": "CPU Core Usage vs. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      cluster=\"$cluster\",\r\n      resource=\"cpu\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-applicationset-controller.*\"\r\n    }\r\n  )\r\n)",
     "legendFormat": "limit"
    },
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      cluster=\"$cluster\",\r\n      resource=\"cpu\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-applicationset-controller.*\"\r\n    }\r\n  )\r\n)",
     "legendFormat": "request"
    },
    {
     "expr": "max by (pod) (\r\n  irate(container_cpu_usage_seconds_total{cluster=\"$cluster\", container=\"applicationset-controller\"}[$__interval]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\r\n  max by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      cluster=\"$cluster\",\r\n      resource=\"memory\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-applicationset-controller.*\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "limit"
    },
    {
     "expr": "max(\r\n  max by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      cluster=\"$cluster\",\r\n      resource=\"memory\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-applicationset-controller.*\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "request"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{cluster=\"$cluster\", container=~\"applicationset-controller.*\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\r\nkube_pod_container_status_last_terminated_reason{\r\n  pod=~\"applicationset-controller.*\"\r\n} != 0\r\n",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  { "title": "ArgoCD / dex-server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU Core Usage vs. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      cluster=\"$cluster\",\r\n      resource=\"cpu\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-dex-server.*\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "limit"
    },
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      cluster=\"$cluster\",\r\n      resource=\"cpu\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-dex-server.*\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "request"
    },
    {
     "expr": "max by (pod) (\r\n  irate(container_cpu_usage_seconds_total{cluster=\"$cluster\", container=\"dex-server\"}[$__interval]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\r\n  max by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      cluster=\"$cluster\",\r\n      resource=\"memory\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-dex-server.*\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "limit"
    },
    {
     "expr": "max(\r\n  max by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      cluster=\"$cluster\",\r\n      resource=\"memory\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-dex-server.*\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "request"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", container=~\"dex-server\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\", pod=~\"argocd-dex-server.*\"} != 0",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  {
   "title": "ArgoCD / notifications-controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 }
  },
  {
   "title": "CPU Core Usage vs. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      cluster=\"$cluster\",\r\n      resource=\"cpu\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-notifications-controller.*\"\r\n    }\r\n  )\r\n)",
     "legendFormat": "{{pod}} limit"
    },
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      cluster=\"$cluster\",\r\n      resource=\"cpu\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-notifications-controller.*\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "{{pod}} request"
    },
    {
     "expr": "max by (pod) (\r\n  irate(container_cpu_usage_seconds_total{cluster=\"$cluster\", container=\"notifications-controller\"}[$__interval]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\r\n  max by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      cluster=\"$cluster\",\r\n      resource=\"memory\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-notifications-controller.*\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "limit"
    },
    {
     "expr": "max(\r\n  max by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      cluster=\"$cluster\",\r\n      resource=\"memory\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-notifications-controller.*\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "request"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=\"$cluster\", container=~\"notifications-controller\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\", pod=~\"argocd-notifications-controller.*\"} != 0",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  { "title": "ArgoCD/ redis-ha-haproxy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "CPU Core Usage vs. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      cluster=\"$cluster\",\r\n      resource=\"cpu\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-redis-ha-haproxy.*\"\r\n    }\r\n  )\r\n)",
     "legendFormat": "limit"
    },
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      cluster=\"$cluster\",\r\n      resource=\"cpu\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-redis-ha-haproxy.*\"\r\n    }\r\n  )\r\n)",
     "legendFormat": "request"
    },
    {
     "expr": "max by (pod) (\r\n  irate(container_cpu_usage_seconds_total{cluster=\"$cluster\", container=\"haproxy\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\r\n  max by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      cluster=\"$cluster\",\r\n      resource=\"memory\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-redis-ha-haproxy.*\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "limit"
    },
    {
     "expr": "max(\r\n  max by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      cluster=\"$cluster\",\r\n      resource=\"memory\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-redis-ha-haproxy.*\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "request"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{cluster=\"$cluster\",container=\"haproxy\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\", pod=~\"argocd-redis-ha-haproxy.*\"} != 0",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  { "title": "ArgoCD / redis-ha-server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "CPU Core Usage vs. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      cluster=\"$cluster\",\r\n      resource=\"cpu\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-redis-ha-server.*\"\r\n    }\r\n  )\r\n)",
     "legendFormat": "limit"
    },
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      cluster=\"$cluster\",\r\n      resource=\"cpu\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-redis-ha-server.*\"\r\n    }\r\n  )\r\n)",
     "legendFormat": "request"
    },
    {
     "expr": "max by (pod) (\r\n  irate(container_cpu_usage_seconds_total{\r\n    cluster=\"$cluster\",\r\n    container=~\"redis|sentinel|split-brain-fix\"\r\n  }[$__interval])\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\r\n  max by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      cluster=\"$cluster\",\r\n      resource=\"memory\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-redis-ha-server.*\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "limit"
    },
    {
     "expr": "max(\r\n  max by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      cluster=\"$cluster\",\r\n      resource=\"memory\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-redis-ha-server.*\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "request"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{cluster=\"$cluster\", container=~\"redis|sentinel|split-brain-fix\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\", pod=~\"argocd-redis-ha-server.*\"} != 0",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  { "title": "ArgoCD / repo-server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "CPU Core Usage vs. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      cluster=\"$cluster\",\r\n      resource=\"cpu\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-repo-server.*\"\r\n    }\r\n  )\r\n)",
     "legendFormat": "limit"
    },
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      cluster=\"$cluster\",\r\n      resource=\"cpu\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-repo-server.*\"\r\n    }\r\n  )\r\n)",
     "legendFormat": "request"
    },
    {
     "expr": "max by (pod) (\r\n  irate(container_cpu_usage_seconds_total{cluster=\"$cluster\", container=\"repo-server\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\r\n  max by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      cluster=\"$cluster\",\r\n      resource=\"memory\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-repo-server.*\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "limit"
    },
    {
     "expr": "max(\r\n  max by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      cluster=\"$cluster\",\r\n      resource=\"memory\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-repo-server.*\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "request"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{cluster=\"$cluster\",container=\"repo-server\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\", pod=~\"repo-server.*\"} != 0",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  { "title": "ArgoCD / server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "CPU Core Usage vs. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      cluster=\"$cluster\",\r\n      resource=\"cpu\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-server.*\"\r\n    }\r\n  )\r\n)",
     "legendFormat": "limit"
    },
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      cluster=\"$cluster\",\r\n      resource=\"cpu\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-server.*\"\r\n    }\r\n  )\r\n)",
     "legendFormat": "request"
    },
    {
     "expr": "max by (pod) (\r\n  irate(container_cpu_usage_seconds_total{cluster=\"$cluster\", container=\"server\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\r\n  max by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      cluster=\"$cluster\",\r\n      resource=\"memory\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-server.*\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "limit"
    },
    {
     "expr": "max(\r\n  max by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      cluster=\"$cluster\",\r\n      resource=\"memory\",\r\n      namespace=\"argocd\",\r\n      pod=~\"argocd-server.*\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "request"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{cluster=\"$cluster\",container=\"server\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{cluster=\"$cluster\", pod=~\"server.*\"} != 0",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  }
 ]
}