apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nodejs-app
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - merge:
        mergeKeys:
          - server
        generators:
          - clusters:
              selector:
                matchExpressions:
                  - key: enable_nodejs_app
                    operator: In
                    values: ['true']
              values:
                repoURL: https://github.com/txack/nodejs-app.git
                targetRevision: main
                path: k8s
          - clusters:
              selector:
                matchLabels:
                  env: lab

  template:
    metadata:
      name: "nodejs-app-{{.name}}"
    spec:
      project: apps
      source:
        repoURL: '{{ .values.repoURL }}'
        targetRevision: '{{ .values.targetRevision }}'
        path: '{{ .values.path }}'
      destination:
        name: '{{ .name }}'
        namespace: nodejs-app
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
