apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: otel
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - merge:
        mergeKeys:
          - server
        generators:
          - clusters:
              selector:
                matchExpressions:
                  - key: enable_otel
                    operator: In
                    values: ['true']
              values:
                chart: opentelemetry-kube-stack
                chartRepository: https://open-telemetry.github.io/opentelemetry-helm-charts
          - clusters:
              selector:
                matchLabels:
                  env: lab
              values:
                chartVersion: 0.15.2

  template:
    metadata:
      name: "otel-{{.name}}"
      annotations:
        argocd.argoproj.io/manifest-generate-paths: "/values/otel/{{ .name }}"
    spec:
      project: addons
      sources:
        - repoURL: '{{ .values.chartRepository}}'
          targetRevision: '{{ .values.chartVersion}}'
          chart: '{{ .values.chart}}'
          helm:
            releaseName: otel
            valueFiles:
              - $repo/values/otel/{{ .name }}/values.yaml
        - repoURL: https://github.com/fjvi13/homelab-kubernetes-gitops.git
          targetRevision: HEAD
          ref: repo
      destination:
        name: '{{ .name }}'
        namespace: otel-system
      syncPolicy:
        syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true