{
 "title": "Addon health (in progress)",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(kube_pod_info,cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{cluster=\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "External Secrets Operator (ESO) (in progress)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 }
  },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 6 },
   "options": {
    "content": "![filebeat](https://cdn.iconscout.com/icon/free/png-512/free-elastic-search-logo-icon-svg-download-png-3029971.png?f=webp&w=256)"
   }
  },
  {
   "title": "New panel",
   "type": "stat",
   "gridPos": { "h": 9, "w": 2, "x": 2, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(\r\n  sum by (container) (\r\n      kube_pod_container_info{\r\n        cluster=\"$cluster\",\r\n        pod=~\"external-secrets.*\",\r\n        container!=\"\"\r\n      }\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Core Usage vs. Limit (external-secrets)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 4, "y": 6 },
   "targets": [
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      cluster=\"$cluster\",\r\n      resource=\"cpu\",\r\n      namespace=\"external-secrets\",\r\n      pod=~\"external-secrets.*\"\r\n    }\r\n  )\r\n)",
     "legendFormat": "limit"
    },
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      cluster=\"$cluster\",\r\n      resource=\"cpu\",\r\n      namespace=\"external-secrets\",\r\n      pod=~\"external-secrets.*\"\r\n    }\r\n  )\r\n)",
     "legendFormat": "request"
    },
    {
     "expr": "max by (pod) (\r\n  irate(container_cpu_usage_seconds_total{cluster=\"$cluster\", container=~\"external-secrets.*\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(\r\n  sum by (component) (\r\n      kube_pod_container_info{\r\n        cluster=\"$cluster\",\r\n        pod=~\"external-secrets.*\",\r\n        container!=\"\"\r\n        }\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Core Usage vs. Limit (cert-controller)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 9, "x": 4, "y": 15 },
   "targets": [
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      cluster=\"$cluster\",\r\n      resource=\"cpu\",\r\n      namespace=\"external-secrets\",\r\n      pod=~\"cert-controller.*\"\r\n    }\r\n  )\r\n)",
     "legendFormat": "limit"
    },
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      cluster=\"$cluster\",\r\n      resource=\"cpu\",\r\n      namespace=\"external-secrets\",\r\n      pod=~\"cert-controller.*\"\r\n    }\r\n  )\r\n)",
     "legendFormat": "request"
    },
    {
     "expr": "max by (pod) (\r\n  irate(container_cpu_usage_seconds_total{cluster=\"$cluster\", container=~\"cert-controller.*\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Filebeat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 25 },
   "options": {
    "content": "![filebeat](https://cdn.iconscout.com/icon/free/png-512/free-elastic-search-logo-icon-svg-download-png-3029971.png?f=webp&w=256)"
   }
  },
  {
   "title": "CPU Core Usage vs. Limit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 2, "y": 25 },
   "targets": [
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      cluster=\"$cluster\",\r\n      resource=\"cpu\",\r\n      namespace=\"filebeat\",\r\n      pod=~\"filebeat.*\"\r\n    }\r\n  )\r\n)",
     "legendFormat": "limit"
    },
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      cluster=\"$cluster\",\r\n      resource=\"cpu\",\r\n      namespace=\"filebeat\",\r\n      pod=~\"filebeat.*\"\r\n    }\r\n  )\r\n)",
     "legendFormat": "request"
    },
    {
     "expr": "max by (pod) (\r\n  irate(container_cpu_usage_seconds_total{cluster=\"$cluster\", container=\"filebeat\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 13, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      cluster=\"$cluster\",\r\n      resource=\"memory\",\r\n      namespace=\"filebeat\",\r\n      pod=~\"filebeat.*\"\r\n    }\r\n  )\r\n)",
     "legendFormat": "limit"
    },
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      cluster=\"$cluster\",\r\n      resource=\"memory\",\r\n      namespace=\"filebeat\",\r\n      pod=~\"filebeat.*\"\r\n    }\r\n  )\r\n)",
     "legendFormat": "request"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{cluster=\"$cluster\",container=\"filebeat\"}[$__interval])) by (pod)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Pods",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(\r\n  sum by (component) (\r\n      kube_pod_container_info{\r\n        cluster=\"$cluster\",\r\n        pod=~\"filebeat.*\",\r\n        container!=\"\"\r\n        }\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  { "title": "Filebeat", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } }
 ]
}