crds:
  enabled: true

defaultRules:
  create: true
  rules:
    alertmanager: true
    etcd: false
    configReloaders: false
    general: false
    k8sContainerCpuUsageSecondsTotal: false
    k8sContainerMemoryCache: false
    k8sContainerMemoryRss: false
    k8sContainerMemorySwap: false
    k8sContainerResource: false
    k8sContainerMemoryWorkingSetBytes: false
    k8sPodOwner: false
    kubeApiserverAvailability: false
    kubeApiserverBurnrate: false
    kubeApiserverHistogram: false
    kubeApiserverSlos: false
    kubeControllerManager: false
    kubelet: false
    kubeProxy: false
    kubePrometheusGeneral: false
    kubePrometheusNodeRecording: false
    kubernetesApps: false
    kubernetesResources: false
    kubernetesStorage: false
    kubernetesSystem: false
    kubeSchedulerAlerting: false
    kubeSchedulerRecording: false
    kubeStateMetrics: false
    network: false
    node: false
    nodeExporterAlerting: false
    nodeExporterRecording: false
    prometheus: true
    prometheusOperator: true
    windows: false

## Provide custom recording or alerting rules to be deployed into the cluster.
##
additionalPrometheusRulesMap:
 rule-name:
   groups:
   - name: custom.rules
     rules:
      - alert: ClusterDown
        annotations:
          summary: Cluster {{ $labels.cluster }} is down
          description: The Prometheus instance for cluster {{ $labels.cluster }} is either down or missing.
        expr: |
          max by (cluster) (
            max_over_time(
              up{job="prometheus-kube-prometheus-prometheus", namespace="monitoring"}[5d]
            )
            or
            max_over_time(
              up{pod=~"opentelemetry-kube-stack-prometheus-collector-.*", namespace="otel-system"}[5d]
            )
          )
          unless
          on (cluster)
          max by (cluster) (
            up{job="prometheus-kube-prometheus-prometheus", namespace="monitoring"} == 1
            or
            up{pod=~"opentelemetry-kube-stack-prometheus-collector-.*", namespace="otel-system"} == 1
          ) > 0
        for: 5m
        labels:
          severity: critical
          namespace: monitoring

alertmanager:
  enabled: true
  fullnameOverride: "alertmanager"
  service:
    enabled: true
    port: 9093
    type: ClusterIP
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
    unhealthyPodEvictionPolicy: AlwaysAllow
  serviceMonitor:
    selfMonitor: true
    interval: ""

  route:
    main:
      # -- Enables or disables the route
      enabled: false

      # -- Set the route apiVersion, e.g. gateway.networking.k8s.io/v1 or gateway.networking.k8s.io/v1alpha2
      apiVersion: gateway.networking.k8s.io/v1
      # -- Set the route kind
      # Valid options are GRPCRoute, HTTPRoute, TCPRoute, TLSRoute, UDPRoute
      kind: HTTPRoute

      annotations: {}
      labels: {}

      hostnames:
        - alertmanager.lab
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: lab-gateway
          namespace: istio-system
          sectionName: http

      # -- create http route for redirect (https://gateway-api.sigs.k8s.io/guides/http-redirect-rewrite/#http-to-https-redirects)
      ## Take care that you only enable this on the http listener of the gateway to avoid an infinite redirect.
      ## matches, filters and additionalRules will be ignored if this is set to true. Be are
      httpsRedirect: false

      matches:
        - path:
            type: PathPrefix
            value: /

      ## Filters define the filters that are applied to requests that match this rule.
      filters: []

      ## Additional custom rules that can be added to the route
      additionalRules: []

  alertmanagerSpec:
    image:
      registry: quay.io
      repository: prometheus/alertmanager
      tag: v0.33.0
      sha: ""
      pullPolicy: IfNotPresent
    replicas: 1
    ## Time duration Alertmanager shall retain data for. Default is '120h', and must match the regular expression
    ## [0-9]+(ms|s|m|h) (milliseconds seconds minutes hours).
    ##
    retention: 120h
    resources: {}

grafana:
  enabled: false
  adminUser: labuser
  adminPassword: labpassword
  ingress:
    enabled: true
    hosts: 
      - grafana2.lab
  sidecar:
    datasources:
      enabled: true
      defaultDatasourceEnabled: true
      isDefaultDatasource: true
      name: Prometheus
      uid: prometheus
      url: http://thanos-query-frontend.monitoring.svc.cluster.local:9090

kubelet:
  enabled: true
  namespace: kube-system
  serviceMonitor:
    interval: "30s"

kube-state-metrics:
  fullnameOverride: "kube-state-metrics"
  prometheus:
    monitor:
      enabled: true
      interval: ""

nodeExporter:
  enabled: true
prometheus-node-exporter:
  fullnameOverride: "node-exporter"
  prometheus:
    monitor:
      enabled: true
      interval: "30s"

prometheusOperator:
  fullnameOverride: "prometheus-operator"

  image:
    registry: quay.io
    repository: prometheus-operator/prometheus-operator
    tag: v0.92.0
    sha: ""
    pullPolicy: IfNotPresent

  podDisruptionBudget:
    enabled: true
    minAvailable: 1
    unhealthyPodEvictionPolicy: AlwaysAllow
  resources:
    limits:
      cpu: 400m
      memory: 600Mi
    requests:
      cpu: 200m
      memory: 300Mi

  ## Create Endpoints objects for kubelet targets.
  kubeletEndpointsEnabled: false
  ## Create EndpointSlice objects for kubelet targets.
  kubeletEndpointSliceEnabled: true

  prometheusConfigReloader:
    resources:
      requests:
        cpu: 200m
        memory: 50Mi
      limits:
        cpu: 200m
        memory: 50Mi

# prometheus:
#   fullnameOverride: "prometheus-server"
#   agentMode: false
#   serviceMonitor:
#     selfMonitor: true
#   prometheusSpec:
#     scrapeInterval: "60s"
#     replicas: 2
#     retention: 2h
#     externalLabels:
#       cluster: "central-cluster-dev"
#     replicaExternalLabelName: "prometheus_replica"
#     ruleSelector:
#       matchExpressions:
#         - key: release
#           operator: In
#           values:
#             - thanos
#     serviceMonitorSelector:
#       matchExpressions:
#         - key: release
#           operator: In
#           values:
#             - thanos
#             - kube-prometheus-stack
#     remoteWrite:
#     - url: http://thanos-receive.monitoring.svc.cluster.local:10908/api/v1/receive
#       # headers:
#       #   THANOS-TENANT: "central-cluster-dev"
#       queueConfig:
#         capacity: 10000
#         maxShards: 50
#         minShards: 1
#         maxSamplesPerSend: 5000
#         batchSendDeadline: 5s
#         minBackoff: 30ms
#         maxBackoff: 5s
#       # Aumentar timeout para evitar "context deadline exceeded"
#       remoteTimeout: 30s
#       sendExemplars: false
#     serviceDiscoveryRole: "EndpointSlice"
#     resources:
#       limits:
#         cpu: 1
#         memory: 1Gi
#       requests:
#         cpu: 500m
#         memory: 512Mi




prometheus:
  fullnameOverride: "prometheus-agent"
  agentMode: true
  prometheusSpec:
    scrapeInterval: "60s"
    replicas: 1
    replicaExternalLabelName: "prometheus_replica"
    serviceMonitorSelector:
      matchExpressions:
        - key: release
          operator: In
          values:
            - thanos
            - prometheus
    externalLabels:
      cluster: "central-cluster"
    remoteWrite:
    - url: http://thanos-receive.monitoring.svc.cluster.local:10908/api/v1/receive
      # headers:
      #   THANOS-TENANT: "central-cluster-dev"
      queueConfig:
        capacity: 10000
        maxShards: 50
        minShards: 1
        maxSamplesPerSend: 5000
        batchSendDeadline: 5s
        minBackoff: 30ms
        maxBackoff: 5s
      # Aumentar timeout para evitar "context deadline exceeded"
      remoteTimeout: 30s
      sendExemplars: false
    serviceDiscoveryRole: "EndpointSlice"
    resources: {}
      # limits:
      #   cpu: 1
      #   memory: 1Gi
      # requests:
      #   cpu: 500m
      #   memory: 512Mi
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
    unhealthyPodEvictionPolicy: AlwaysAllow

thanosRuler:
  enabled: true

  podDisruptionBudget:
    enabled: true
    minAvailable: 1
    unhealthyPodEvictionPolicy: AlwaysAllow

  route:
    main:
      enabled: false
      apiVersion: gateway.networking.k8s.io/v1
      kind: HTTPRoute

      annotations: {}
      labels: {}

      hostnames:
        - ruler.lab
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: lab-gateway
          namespace: istio-system
          sectionName: http
      httpsRedirect: false

      matches:
        - path:
            type: PathPrefix
            value: /
      filters: []
      additionalRules: []

  serviceMonitor:
    selfMonitor: true
    
  thanosRulerSpec:
    image:
      registry: quay.io
      repository: thanos/thanos
      tag: v0.39.2
      sha: ""

    ## If true, a nil or {} value for thanosRuler.thanosRulerSpec.ruleSelector will cause the
    ## prometheus resource to be created with selectors based on values in the helm deployment,
    ## which will also match the PrometheusRule resources created
    ##
    ruleSelectorNilUsesHelmValues: true
    ruleSelector:
      matchExpressions:
        - key: release
          operator: In
          values:
            - thanos
            - prometheus

    logFormat: logfmt
    logLevel: info
    replicas: 1
    evaluationInterval: 1m

    storage: {}

    alertmanagersConfig:
      secret:
        alertmanagers:
          - static_configs:
              - dns+alertmanager-operated.monitoring.svc.cluster.local:9093
            scheme: http
            api_version: v2
            timeout: 10s

    ## If true, http://{{ template "kube-prometheus-stack.thanosRuler.name" . }}.{{ template "kube-prometheus-stack.namespace" . }}:{{ .Values.thanosRuler.service.port }}
    ## will be used as value for externalPrefix
    externalPrefixNilUsesHelmValues: true

    ## The route prefix ThanosRuler registers HTTP handlers for. This is useful, if using ExternalURL and a proxy is rewriting HTTP routes of a request, and the actual ExternalURL is still true,
    ## but the server serves requests under a different route prefix. For example for use with kubectl proxy.
    ##
    routePrefix: /

    ## Labels by name to drop before sending to alertmanager
    ## Maps to the --alert.label-drop flag of thanos ruler.
    alertDropLabels: []

    ## QueryEndpoints defines Thanos querier endpoints from which to query metrics.
    ## Maps to the --query flag of thanos ruler.
    queryEndpoints: [dnssrv+_http._tcp.thanos-query.monitoring.svc.cluster.local]

    ## Labels configure the external label pairs to ThanosRuler. A default replica
    ## label `thanos_ruler_replica` will be always added as a label with the value
    ## of the pod's name and it will be dropped in the alerts.
    labels: {}

    ## If set to true all actions on the underlying managed objects are not going to be performed, except for delete actions.
    ##
    paused: false

    additionalArgs:
      - name: alert.query-url
        value: "http://query.lab"
      - name: remote-write.config
        value: |-
          "remote_write":
          - "name": "receiver"
            "remote_timeout": "30s"
            "url": "http://thanos-receive.monitoring.svc.cluster.local:10908/api/v1/receive"
            "queue_config":
              "capacity": 500
              "max_shards": 30
              "max_samples_per_send": 200

    resources: {}
    # requests:
    #   memory: 400Mi
