---
# Default values for eck-stack.
# This is a YAML-formatted file.

# If enabled, will use the eck-elasticsearch chart and deploy an Elasticsearch resource.
#
eck-elasticsearch:
  enabled: true
  fullnameOverride: elasticsearch
  version: 9.4.2
  http:
    tls:
      selfSignedCertificate:
        disabled: true
  nodeSets:
  - name: default
    count: 1
    config:
      node.store.allow_mmap: false
      node.roles: ["master", "data", "ingest", "transform"]
    podTemplate:
      spec:
        containers:
        - name: elasticsearch
          resources:
            limits:
              memory: 2Gi
              cpu: 1000m
    volumeClaimTemplates:
    - metadata:
        name: elasticsearch-data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 10Gi
        storageClassName: topolvm-provisioner


# If enabled, will use the eck-kibana chart and deploy a Kibana resource.
#
eck-kibana:
  enabled: true
  fullnameOverride: kibana
  version: 9.4.2
  # This is also adjusting the kibana reference to the elasticsearch resource named previously so that
  # both the eck-elasticsearch and the eck-kibana chart work together by default in the eck-stack chart.
  elasticsearchRef:
    name: elasticsearch
  podTemplate:
    spec:
      containers:
      - name: kibana
        resources:
          limits:
            memory: 2Gi
            cpu: 1000m
          requests:
            cpu: 500m
            memory: 1Gi
  spec:
    http:
      tls:
        selfSignedCertificate:
          disabled: true
  

# If enabled, will use the eck-agent chart and deploy an Elastic Agent instance.
#
eck-agent:
  enabled: false

# If enabled, will use the eck-fleet-server chart and deploy a Fleet Server resource.
#
eck-fleet-server:
  enabled: true
  fullnameOverride: fleet-server
  version: 9.3.0
  policyID: 020c969a-ef88-4319-9780-0a7865276f47
  elasticsearchRefs: 
  - name: elasticsearch
  kibanaRef:
    name: kibana
  deployment:
    replicas: 1
    podTemplate:
      spec:
        serviceAccountName: fleet-server
        automountServiceAccountToken: true
        
# If enabled, will use the eck-beats chart and deploy a Beats resource.
#
eck-beats:
  enabled: false

# If enabled, will use the eck-logstash chart and deploy a Logstash resource.
#
eck-logstash:
  enabled: false

# If enabled, will use the eck-apm-server chart and deploy a standalone APM Server resource.
#
eck-apm-server:
  enabled: false

# If enabled, will use the eck-enterprise-search chart and deploy a Enterprise Search resource.
#
eck-enterprise-search:
  enabled: false

# If enabled, will use the eck-autoops-agent-policy chart and deploy an AutoOps Agent.
#
eck-autoops-agent-policy:
  enabled: false

# If enabled, will use the eck-package-registry chart and deploy a Package Registry resource.
#
eck-package-registry:
  enabled: false

# extraObjects allows injecting additional Kubernetes resources into the chart.
# These resources will be created/deleted alongside the chart release.
# The value is a list of strings, each string is a YAML manifest.
# Helm templating is supported within each manifest.
# Example:
# extraObjects:
#   - |
#     apiVersion: v1
#     kind: ConfigMap
#     metadata:
#       name: {{ include "eck-stack.fullname" . }}-extra-config
#       namespace: {{ .Release.Namespace }}
#     data:
#       key: value
extraObjects:
  - |
    apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    metadata:
      name: kibana
      namespace: {{ .Release.Namespace }}
    spec:
      hostnames:
        - kibana.lab
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: lab-gateway
          namespace: istio-system
          sectionName: http
      rules:
        - backendRefs:
            - group: ""
              kind: Service
              name: kibana-kb-http
              port: 5601
              weight: 1
          matches:
            - path:
                type: PathPrefix
                value: /
  - |
    apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    metadata:
      name: elasticsearch
      namespace: {{ .Release.Namespace }}
    spec:
      hostnames:
        - elasticsearch.lab
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: lab-gateway
          namespace: istio-system
          sectionName: http
      rules:
        - backendRefs:
            - group: ""
              kind: Service
              name: elasticsearch-es-http
              port: 9200
              weight: 1
          matches:
            - path:
                type: PathPrefix
                value: /
              
  - |
    apiVersion: gateway.networking.k8s.io/v1
    kind: HTTPRoute
    metadata:
      name: fleet-server
      namespace: {{ .Release.Namespace }}
    spec:
      hostnames:
        - fleet.lab
      parentRefs:
        - group: gateway.networking.k8s.io
          kind: Gateway
          name: lab-gateway
          namespace: istio-system
          sectionName: http
      rules:
        - backendRefs:
            - group: ""
              kind: Service
              name: fleet-server-agent-http
              port: 8220
              weight: 1
          matches:
            - path:
                type: PathPrefix
                value: /