{
 "title": "Thanos / Overview",
 "description": "This dashboard provides a resource usage overview of the Thanos components Querier, Query-Frontend, Compacter and Store.\r\n\r\nIt includes CPU and Memory requests, limits and usage. In addition, the last termination reason is plotted and the cache hit ratio is available.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "![logo](https://repository-images.githubusercontent.com/109162639/97e49180-661b-11e9-9882-fdc44b74debd)"
   }
  },
  {
   "title": "Number of Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 21, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "\r\nsort_desc(\r\n  sum by (component) (\r\n    label_replace(\r\n      kube_pod_container_info{\r\n        pod=~\"thanos-(compactor|storegateway|ruler|receive(?:-distributor)?|query(?:-frontend)?).*\",\r\n        container!=\"\"\r\n      },\r\n      \"component\", \"$1\", \"pod\",\r\n      \"thanos-(compactor|storegateway|ruler|receive(?:-distributor)?|query(?:-frontend)?).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "{{app_kubernetes_io_component}}"
    }
   ]
  },
  { "title": "Thanos / Query", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Core Usage vs. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      resource=\"cpu\",\r\n      namespace=\"monitoring\",\r\n      pod=~\"thanos-query.*\",\r\n      pod!~\"thanos-query-frontend-.*\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "limit"
    },
    {
     "expr": "max by (pod) (\r\n  irate(container_cpu_usage_seconds_total{container=\"query\"}[$__interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "\r\nmax(\r\n  max by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      resource=\"memory\",\r\n      namespace=\"monitoring\",\r\n      pod=~\"^thanos-query(-.*)?$\",\r\n      pod!~\"^thanos-query-distributor(-.*)?$\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{container=\"query\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\r\nkube_pod_container_status_last_terminated_reason{\r\n  pod=~\"thanos-query.*\",\r\n  pod!~\"thanos-query-frontend.*\"\r\n} != 0\r\n",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  { "title": "Thanos / Query Frontend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "CPU Core Usage vs. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"monitoring\", pod=~\"thanos-query-frontend.*\"}\r\n  )\r\n)\r\n",
     "legendFormat": "limit"
    },
    {
     "expr": "max by (pod) (\r\n  irate(container_cpu_usage_seconds_total{container=\"query-frontend\"}[$__interval]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\r\n  max by (pod) (\r\n    kube_pod_container_resource_limits{resource=\"memory\", namespace=\"monitoring\", pod=~\"thanos-query-frontend.*\"}\r\n  )\r\n)\r\n",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{container=~\"query-frontend.*\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "\r\nkube_pod_container_status_last_terminated_reason{\r\n  pod=~\"thanos-query-frontend.*\"\r\n} != 0\r\n",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  { "title": "Thanos / Compact", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "CPU Core Usage vs. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"monitoring\", pod=~\"thanos-compactor.*\"}\r\n  )\r\n)\r\n",
     "legendFormat": "limit"
    },
    {
     "expr": "max by (pod) (\r\n  irate(container_cpu_usage_seconds_total{container=\"compactor\"}[$__interval]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\r\n  max by (pod) (\r\n    kube_pod_container_resource_limits{resource=\"memory\", namespace=\"monitoring\", pod=~\"thanos-compactor.*\"}\r\n  )\r\n)",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container=~\"compactor\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 24 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{pod=~\"thanos-compactor.*\"} != 0",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  { "title": "Thanos / Store", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "CPU Core Usage vs. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"monitoring\", pod=~\"thanos-store.*\"}\r\n  )\r\n)\r\n",
     "legendFormat": "{{pod}} limit"
    },
    {
     "expr": "max by (pod) (\r\n  irate(container_cpu_usage_seconds_total{container=\"storegateway\"}[$__interval]))",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(sum(kube_pod_container_resource_limits{container=~\"storegateway\"}) by (pod))",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(container_memory_working_set_bytes{container=~\"storegateway\", pod!=\"\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{pod=~\"thanos-storegateway.*\"} != 0",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n  rate(\n    thanos_store_index_cache_hits_total[$__rate_interval]\n  )\n)\n/\nsum(\n  rate(\n    thanos_store_index_cache_requests_total[$__rate_interval]\n  ) \n)",
     "legendFormat": "Hit Ratio"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(thanos_store_index_cache_hits_total[5m])",
     "legendFormat": "{{item_type}} - {{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "bucket_store_series_fetch_duration_seconds_count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(thanos_bucket_store_series_fetch_duration_seconds_count[$__rate_interval])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Thanos / Receive", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "CPU Core Usage vs. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      namespace=\"monitoring\",\r\n      resource=\"cpu\",\r\n      container=\"receive\",\r\n      pod=~\"^thanos-receive($|-[0-9]+)$\"\r\n    }\r\n  )\r\n)",
     "legendFormat": "limit"
    },
    {
     "expr": "\r\nmax by (pod) (\r\n  irate(\r\n    container_cpu_usage_seconds_total{\r\n      namespace=\"monitoring\",\r\n      pod=~\"^thanos-receive($|-[0-9]+$)\",\r\n      container!=\"\"\r\n    }[2m]\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\r\n  max by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      resource=\"memory\",\r\n      namespace=\"monitoring\",\r\n      pod=~\"thanos-receive.*\",\r\n      pod!~\"thanos-receive-distributor.*\"\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "limit"
    },
    {
     "expr": "\r\nsum(container_memory_working_set_bytes{container=~\"receive\",pod=~\"thanos-receive.*\",pod!~\"thanos-receive-distributor.*\"}) by (pod)\r\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 50 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{pod=~\"thanos-receive.*\"} != 0",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  { "title": "Thanos / Receive Distributor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "CPU Core Usage vs. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      namespace=\"monitoring\",\r\n      resource=\"cpu\",\r\n      container=\"receive\",\r\n      pod=~\"^thanos-receive-distributor.*\"\r\n    }\r\n  )\r\n)",
     "legendFormat": "limit"
    },
    {
     "expr": "max by (pod) (\r\n  irate(\r\n    container_cpu_usage_seconds_total{\r\n      namespace=\"monitoring\",\r\n      pod=~\"^thanos-receive-distributor.*\"\r\n    }[$__rate_interval]\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\r\n  max by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      resource=\"memory\",\r\n      namespace=\"monitoring\",\r\n      pod=~\"thanos-receive-distributor.*\",\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "limit"
    },
    {
     "expr": "\r\n\r\n\r\nsum(container_memory_working_set_bytes{namespace=\"monitoring\",container=~\"receive\",pod=~\"thanos-receive-distributor.*\"}) by (pod)\r\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 59 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{pod=~\"thanos-receive-distributor.*\"} != 0",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  { "title": "Thanos / Ruler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 67 } },
  {
   "title": "CPU Core Usage vs. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{resource=\"cpu\", namespace=\"monitoring\", pod=~\"thanos-ruler.*\"}\r\n  )\r\n)",
     "legendFormat": "limit"
    },
    {
     "expr": "max by (pod) (irate((container_cpu_usage_seconds_total{container=\"ruler\"}[$__interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage v. Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(\r\n  max by (pod) (\r\n    kube_pod_container_resource_limits{resource=\"memory\", namespace=\"monitoring\", pod=~\"thanos-ruler.*\"}\r\n  )\r\n)",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{container=\"ruler\"}[$__interval])) by (pod)\r\n\r\n",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 68 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{pod=~\"thanos-ruler.*\"} != 0",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  }
 ]
}