crds:
  enabled: true

defaultRules:
  create: false

alertmanager:
  enabled: false

grafana:
  enabled: false

kubernetesServiceMonitors:
  enabled: true

kubelet:
  enabled: true
  namespace: kube-system
  serviceMonitor:
    enabled: true
    kubelet: true
    interval: "30s"

kubeStateMetrics:
  enabled: true
kube-state-metrics:
  fullnameOverride: "kube-state-metrics"
  prometheus:
    monitor:
      enabled: true
      interval: ""

nodeExporter:
  enabled: true
prometheus-node-exporter:
  fullnameOverride: "node-exporter"
  prometheus:
    monitor:
      enabled: true
      interval: "30s"

prometheusOperator:
  fullnameOverride: "prometheus-operator"
  revisionHistoryLimit: 1
  resources:
    limits:
      cpu: 400m
      memory: 600Mi
    requests:
      cpu: 200m
      memory: 300Mi
  kubeletEndpointsEnabled: false
  kubeletEndpointSliceEnabled: true

  prometheusConfigReloader:
    resources:
      requests:
        cpu: 200m
        memory: 50Mi
      limits:
        cpu: 200m
        memory: 50Mi

prometheus:
  fullnameOverride: "prometheus-agent"
  agentMode: true
  prometheusSpec:
    scrapeInterval: "120s"
    replicas: 1
    externalLabels:
      cluster: "remote-cluster"
    replicaExternalLabelName: "prometheus_replica"
    serviceMonitorSelector:
      matchExpressions:
        - key: release
          operator: In
          values:
            - prometheus
    remoteWrite:
    - url: http://receiver.local/api/v1/receive
      tlsConfig:
      #     caFile: /etc/prometheus/secrets/ca.crt
      #     certFile: /etc/prometheus/secrets/client.crt
      #     keyFile: /etc/prometheus/secrets/client.key
        insecureSkipVerify: true
      queueConfig:
        capacity: 20000
        maxShards: 10
        minShards: 1
        maxSamplesPerSend: 2000
        batchSendDeadline: 10s
        minBackoff: 100ms
        maxBackoff: 10s
        sampleAgeLimit: 2m
      remoteTimeout: 10s
    serviceDiscoveryRole: "EndpointSlice"
    resources: {}
      # limits:
      #   cpu: 1
      #   memory: 1Gi
      # requests:
      #   cpu: 500m
      #   memory: 512Mi
