{
 "title": "Clusters Status",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Total Number of Clusters Writing Metrics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(count by (cluster) (up{job=\"prometheus-kube-prometheus-prometheus\", namespace=\"monitoring\"} == 1) or count by (cluster) (up{pod=~\"opentelemetry-kube-stack-prometheus-collector-.*\", namespace=\"monitoring\"}))",
     "legendFormat": "Total of clusters"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count by (cluster) (up{job=\"prometheus-kube-prometheus-prometheus\", namespace=\"monitoring\"} == 1) or count by (cluster) (up{pod=~\"opentelemetry-kube-stack-prometheus-collector-.*\", namespace=\"monitoring\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "EKS and AKS Clusters",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (cluster) (up{job=\"prometheus-kube-prometheus-prometheus\", namespace=\"monitoring\", cluster=~\".*eks.*\"} == 1) or count by (cluster) (up{pod=~\"opentelemetry-kube-stack-prometheus-collector-.*\", namespace=\"monitoring\", cluster=~\".*eks.*\"}))",
     "legendFormat": "EKS Clusters"
    },
    {
     "expr": "count(count by (cluster) (up{job=\"prometheus-kube-prometheus-prometheus\", namespace=\"monitoring\", cluster=~\".*aks.*\"} == 1) or count by (cluster) (up{pod=~\"opentelemetry-kube-stack-prometheus-collector-.*\", namespace=\"monitoring\", cluster=~\".*aks.*\"}))",
     "legendFormat": "AKS Clusters"
    }
   ]
  },
  {
   "title": "Dev | Pro | Pre | Int Clusters",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (cluster) (up{job=\"prometheus-kube-prometheus-prometheus\", namespace=\"monitoring\", cluster=~\".*-dev$\"} == 1) or count by (cluster) (up{pod=~\"opentelemetry-kube-stack-prometheus-collector-.*\", namespace=\"monitoring\", cluster=~\".*-dev$\"}))",
     "legendFormat": "DEV Clusters"
    },
    {
     "expr": "count(count by (cluster) (up{job=\"prometheus-kube-prometheus-prometheus\", namespace=\"monitoring\", cluster=~\".*-pro$\"} == 1) or count by (cluster) (up{pod=~\"opentelemetry-kube-stack-prometheus-collector-.*\", namespace=\"monitoring\", cluster=~\".*-pro$\"}))",
     "legendFormat": "PRO Clusters"
    },
    {
     "expr": "count(count by (cluster) (up{job=\"prometheus-kube-prometheus-prometheus\", namespace=\"monitoring\", cluster=~\".*-pre$\"} == 1) or count by (cluster) (up{pod=~\"opentelemetry-kube-stack-prometheus-collector-.*\", namespace=\"monitoring\", cluster=~\".*-pre$\"}))",
     "legendFormat": "PRE Clusters"
    },
    {
     "expr": "count(count by (cluster) (up{job=\"prometheus-kube-prometheus-prometheus\", namespace=\"monitoring\", cluster=~\".*-int$\"} == 1) or count by (cluster) (up{pod=~\"opentelemetry-kube-stack-prometheus-collector-.*\", namespace=\"monitoring\", cluster=~\".*-int$\"}))",
     "legendFormat": "INT Clusters"
    }
   ]
  },
  {
   "title": "EKS and AKS Clusters",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count by (cluster) (up{job=\"prometheus-kube-prometheus-prometheus\", namespace=\"monitoring\", cluster=~\".*op.*\"} == 1) or count by (cluster) (up{pod=~\"opentelemetry-kube-stack-prometheus-collector-.*\", namespace=\"monitoring\", cluster=~\".*op.*\"}))",
     "legendFormat": "OP Clusters"
    },
    {
     "expr": "count(count by (cluster) (up{job=\"prometheus-kube-prometheus-prometheus\", namespace=\"monitoring\", cluster=~\".*(kp|4p).*\"} == 1) or count by (cluster) (up{pod=~\"opentelemetry-kube-stack-prometheus-collector-.*\", namespace=\"monitoring\", cluster=~\".*(kp|4p).*\"}))",
     "legendFormat": "Package Clusters"
    }
   ]
  },
  {
   "title": "K8S versions",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count by (version) (\r\n  max by (cluster, version) (\r\n    label_replace(\r\n      kube_node_info,\r\n      \"version\", \"$1\",\r\n      \"kubelet_version\", \"^(v[0-9.]+).*\"\r\n    )\r\n  )\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Status List",
   "type": "table",
   "description": "This table displays the current status (UP/DOWN) of all clusters that have been active in the last 5 days. If a cluster stops sending metrics for more than 5 days, It will disappear from the list.",
   "gridPos": { "h": 30, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sort(\n  max by (cluster) (\n    up{job=\"prometheus-kube-prometheus-prometheus\", namespace=\"monitoring\"}\n    or\n    up{pod=~\"opentelemetry-kube-stack-prometheus-collector-.*\", namespace=\"monitoring\"}\n  )\n  or\n  (\n    max by (cluster) (\n      max_over_time(up{job=\"prometheus-kube-prometheus-prometheus\", namespace=\"monitoring\"}[5d])\n      or\n      max_over_time(up{pod=~\"opentelemetry-kube-stack-prometheus-collector-.*\", namespace=\"monitoring\"}[5d])\n    ) * 0\n  )\n)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}