{
 "title": "K8S Dashboard",
 "description": "【English version】2025.01.25 Updates，kubernetesComprehensive display of resources！Includes K8S Overall Resource Overview、Microservices Resource Details、Pod Resource Details andK8SNetwork Bandwidth，Optimization metrics。https://grafana.com/orgs/starsliao/dashboards",
 "tags": [
  "Prometheus",
  "Kubernetes"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(kube_node_info,cluster)"
    }
   },
   {
    "name": "Node",
    "label": "Nodes",
    "query": {
     "query": "label_values(kube_node_info{cluster=~\"$cluster\"},node)"
    }
   },
   {
    "name": "NameSpace",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_namespace_created{cluster=~\"$cluster\"},namespace)"
    }
   },
   {
    "name": "Container",
    "label": "Microservice (Container Name)",
    "query": {
     "query": "label_values(kube_pod_container_info{cluster=~\"$cluster\",namespace=~\"$NameSpace\"},container)"
    }
   },
   {
    "name": "Pod",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{cluster=~\"$cluster\",namespace=~\"$NameSpace\",container=~\"$Container\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Node Resource Overview：Selected Nodes:【$Node】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Node Memory Ratio",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_working_set_bytes{cluster=~\"$cluster\",container!=\"\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
     "legendFormat": "Memory Utilization"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
     "legendFormat": "Memory Request Rate"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
     "legendFormat": "Memory Limit Rate"
    }
   ]
  },
  {
   "title": "Node CPU Ratio",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",container!=\"\",node=~\"^$Node$\"}[2m])) / sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
     "legendFormat": "CPU Utilization Rate"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
     "legendFormat": "CPU Request Rate"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"}) / sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
     "legendFormat": "CPU Limit Rate"
    }
   ]
  },
  {
   "title": "Nodes with Pod",
   "type": "bargauge",
   "description": "Number of cluster nodes，Nodes POD Number of，NodesPODUpper Limit",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(kube_node_info{cluster=~\"$cluster\"})",
     "legendFormat": "Number of nodes"
    },
    {
     "expr": "count(kube_pod_info{cluster=~\"$cluster\",created_by_kind!~\"<none>|Job\",node=~\"^$Node$\"})",
     "legendFormat": "Pod Number of nodes"
    },
    {
     "expr": "sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"pods\", unit=\"integer\",node=~\"^$Node$\"})",
     "legendFormat": "Upper limit Pod"
    }
   ]
  },
  {
   "title": "Namespace Resource Statistics",
   "type": "table",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kube_pod_info{cluster=~\"$cluster\",node=~\"^$Node$\"}) by (namespace)"
    },
    {
     "expr": "count(kube_service_info{cluster=~\"$cluster\"}) by(namespace)"
    },
    {
     "expr": "count by (namespace)({__name__=~\"kube_deployment_metadata_generation|kube_daemonset_metadata_generation|kube_statefulset_metadata_generation\",cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(kube_configmap_info{cluster=~\"$cluster\"}) by(namespace)",
     "legendFormat": "configmap"
    },
    {
     "expr": "count(kube_secret_info{cluster=~\"$cluster\"}) by(namespace)",
     "legendFormat": "secret"
    }
   ]
  },
  {
   "title": "$NameSpace：Network Overview（Associable nodes and namespaces）",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum (irate(container_network_receive_bytes_total{cluster=~\"$cluster\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m]))*8",
     "legendFormat": "Receive"
    },
    {
     "expr": "sum (irate(container_network_transmit_bytes_total{cluster=~\"$cluster\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m]))*8",
     "legendFormat": "Send"
    }
   ]
  },
  {
   "title": "Node Memory Information",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=~\"$cluster\",container!=\"\",node=~\"^$Node$\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})",
     "legendFormat": "Limits"
    }
   ]
  },
  {
   "title": "Node CPU Number of cores",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
     "legendFormat": "Total Cores"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",id=\"/\",node=~\"^$Node$\"}[2m]))",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})",
     "legendFormat": "Requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})",
     "legendFormat": "Limit"
    }
   ]
  },
  {
   "title": "Node Storage Information",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 3, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum (container_fs_usage_bytes{cluster=~\"$cluster\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) / sum (container_fs_limit_bytes{cluster=~\"$cluster\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})",
     "legendFormat": "Utilization Rate"
    },
    {
     "expr": "sum (container_fs_usage_bytes{cluster=~\"$cluster\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum (container_fs_limit_bytes{cluster=~\"$cluster\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 9 },
   "repeat": "cluster",
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count({__name__=~\"kube_deployment_metadata_generation|kube_daemonset_metadata_generation|kube_statefulset_metadata_generation\",cluster=~\"$cluster\"})",
     "legendFormat": "Workload"
    },
    {
     "expr": "count(kube_pod_info{cluster=~\"$cluster\"})",
     "legendFormat": "Total Pod"
    },
    {
     "expr": "count by(key,cluster)(kube_node_spec_taint{cluster=~\"$cluster\",key=~\"node.kubernetes.io.*\"})",
     "legendFormat": "{{key}}"
    },
    {
     "expr": "count by(cluster)(kube_node_info{cluster=~\"$cluster\"})",
     "legendFormat": "Total Nodes"
    },
    {
     "expr": "count by(cluster)(kube_node_info{cluster=~\"$cluster\"}) - count by(cluster)(kube_node_spec_taint{cluster=~\"$cluster\",key!~\"node.kubernetes.io.*\"})",
     "legendFormat": "Normal Node"
    },
    {
     "expr": "count by(key,cluster)(kube_node_spec_taint{cluster=~\"$cluster\",key!~\"node.kubernetes.io.*\"})",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Memory Usage【$Node】",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})",
     "legendFormat": "Total Node Memory"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=~\"$cluster\",container!=\"\",node=~\"^$Node$\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})",
     "legendFormat": "Total pods requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})",
     "legendFormat": "Total pods limits"
    }
   ]
  },
  {
   "title": "CPU Used Cores【$Node】",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})",
     "legendFormat": "Total Node Cores"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",node=~\"^$Node$\"}[2m]))",
     "legendFormat": "Total pods usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})",
     "legendFormat": "Total pods requests"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})",
     "legendFormat": "Total pods limits"
    }
   ]
  },
  {
   "title": "Pod Number and nodes【$Node】",
   "type": "timeseries",
   "description": "Number of Cluster Nodes，Nodes POD Number of，Nodes POD Upper Limit",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kube_node_info{cluster=~\"$cluster\"})",
     "legendFormat": "Number of nodes"
    },
    {
     "expr": "count(kube_pod_info{cluster=~\"$cluster\",created_by_kind!~\"<none>|Job\",node=~\"^$Node$\"})",
     "legendFormat": "Pod Number"
    },
    {
     "expr": "sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"pods\", unit=\"integer\",node=~\"^$Node$\"})",
     "legendFormat": "Upper Limit Pod"
    }
   ]
  },
  {
   "title": "$Node：Nodes CPU Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",container!=\"\",node=~\"^$Node$\"}[2m]))by (node) / sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})by (node)*100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$Node：Node Memory Breakdown",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=~\"$cluster\",container!=\"\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})by (node)*100",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "$Node：Node Network Overview",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum (irate(container_network_receive_bytes_total{cluster=~\"$cluster\",node=~\"^$Node$\"}[2m]))by (node) *8",
     "legendFormat": "Inflow:{{node}}"
    },
    {
     "expr": "sum (irate(container_network_transmit_bytes_total{cluster=~\"$cluster\",node=~\"^$Node$\"}[2m]))by (node) *8",
     "legendFormat": "Outflows:{{node}}"
    }
   ]
  },
  {
   "title": "$Node：Node Information Detail",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "count(kube_pod_info{cluster=~\"$cluster\",created_by_kind!~\"<none>|Job\",node=~\"^$Node$\"}) by (node)",
     "legendFormat": "pod Number"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",container!=\"\",node=~\"^$Node$\"}[2m])) by (node)"
    },
    {
     "expr": "kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"} - 0"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=~\"$cluster\",container!=\"\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"}) by (node) - 0"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum (container_fs_usage_bytes{cluster=~\"$cluster\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum (container_fs_limit_bytes{cluster=~\"$cluster\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) by (node)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=~\"$cluster\",container!=\"\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})by (node)",
     "legendFormat": "Memory Usage%"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})by (node)",
     "legendFormat": "Memory Requests%"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"memory\", unit=\"byte\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"memory\", unit=\"byte\", node=~\"^$Node$\"})by (node)",
     "legendFormat": "Memory Limit%"
    },
    {
     "expr": "sum (irate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",container!=\"\",node=~\"^$Node$\"}[2m]))by (node) / sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})by (node)",
     "legendFormat": "CPU Usage%"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})by (node)",
     "legendFormat": "CPU Requests%"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"cpu\", unit=\"core\",node=~\"^$Node$\"})by (node) / sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"cpu\", unit=\"core\", node=~\"^$Node$\"})by (node)",
     "legendFormat": "Memory Limit%"
    },
    {
     "expr": "sum (container_fs_usage_bytes{cluster=~\"$cluster\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})by (node) / sum (container_fs_limit_bytes{cluster=~\"$cluster\",device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"})by (node)",
     "legendFormat": "Disk Usage%"
    },
    {
     "expr": "sum(kube_node_status_allocatable{cluster=~\"$cluster\",resource=\"pods\", unit=\"integer\",node=~\"^$Node$\"})by (node)",
     "legendFormat": "PodCaps"
    },
    {
     "expr": "group by (cluster, kubelet_version, node) (kube_node_info{cluster=~\"$cluster\", node=~\"^$Node$\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PVC Storage Usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"})",
     "legendFormat": "{{namespace}}:{{ persistentvolumeclaim }}"
    },
    {
     "expr": "min by (namespace,persistentvolumeclaim) (kubelet_volume_stats_available_bytes{cluster=~\"$cluster\"}) + max by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "max by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"}) /(min by (namespace,persistentvolumeclaim) (kubelet_volume_stats_available_bytes{cluster=~\"$cluster\"}) + max by (namespace,persistentvolumeclaim) (kubelet_volume_stats_used_bytes{cluster=~\"$cluster\"}))*100",
     "legendFormat": "{{namespace}}:{{ persistentvolumeclaim }}"
    },
    {
     "expr": "count by (namespace,persistentvolumeclaim)(kube_pod_spec_volumes_persistentvolumeclaims_info{cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Namespaces CPU Usage kernel(>0.5)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",container !=\"\",container!=\"POD\"}[2m])) by (namespace)>0.5",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "Namespaces WSS Memory Usage (>1G)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=~\"$cluster\",container !=\"\",container!=\"POD\"}) by (namespace) > 1*1024*1024*1024",
     "legendFormat": "{{namespace} {{ pod }}"
    }
   ]
  },
  {
   "title": "Pod Resource Overview：SelectedPod:【$Pod】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 }
  },
  {
   "title": "$Node：Pod Resource Detail(Associable Nodes)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (container, pod,node,namespace) / (sum(container_spec_cpu_quota{cluster=~\"$cluster\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}/100000) by (container, pod,node,namespace)) "
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (container, pod,node,namespace)",
     "legendFormat": "CPUKernel Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"cpu\", unit=\"core\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"cpu\", unit=\"core\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=~\"$cluster\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)/ sum(container_spec_memory_limit_bytes{cluster=~\"$cluster\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)",
     "legendFormat": "wss%"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=~\"$cluster\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)",
     "legendFormat": "wss"
    },
    {
     "expr": "sum (container_memory_rss{cluster=~\"$cluster\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)/ sum(container_spec_memory_limit_bytes{cluster=~\"$cluster\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)",
     "legendFormat": "rss%"
    },
    {
     "expr": "sum (container_memory_rss{cluster=~\"$cluster\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)",
     "legendFormat": "rss"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"memory\", unit=\"byte\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"memory\", unit=\"byte\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "sum(container_fs_usage_bytes{cluster=~\"$cluster\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "kube_pod_container_status_restarts_total{cluster=~\"$cluster\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"} * on (pod) group_left(node) kube_pod_info{cluster=~\"$cluster\",pod=~\"$Pod\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}"
    },
    {
     "expr": "time() - kube_pod_created{cluster=~\"$cluster\",pod=~\"$Pod\",namespace=~\"$NameSpace\"} * on(pod) group_right kube_pod_container_info{cluster=~\"$cluster\",pod=~\"$Pod\",namespace=~\"$NameSpace\",container =~\"$Container\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(container_fs_limit_bytes{cluster=~\"$cluster\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)"
    },
    {
     "expr": "sum(sum(irate(container_network_receive_bytes_total{cluster=~\"$cluster\",pod=~\"$Pod\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{cluster=~\"$cluster\",pod=~\"$Pod\",namespace=~\"$NameSpace\",container =~\"$Container\"}) by(pod) *8",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(sum(irate(container_network_transmit_bytes_total{cluster=~\"$cluster\",pod=~\"$Pod\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{cluster=~\"$cluster\",pod=~\"$Pod\",namespace=~\"$NameSpace\",container =~\"$Container\"}) by(pod) *8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pod Containers CPU Utilization (Maximum100%Associable Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max(irate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (container, pod) / (max(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"cpu\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod)) * 100",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod Container Memory Usage (Associatable Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "max (container_memory_working_set_bytes{cluster=~\"$cluster\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod)/ max(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"memory\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod) * 100",
     "legendFormat": "WSS：{{ pod }}"
    },
    {
     "expr": "max (container_memory_rss{cluster=~\"$cluster\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod)/ max(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"memory\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod) * 100",
     "legendFormat": "RSS：{{ pod }}"
    }
   ]
  },
  {
   "title": "Pod Network bandwidth per second (Associable Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "max(max(irate(container_network_receive_bytes_total{cluster=~\"$cluster\",pod=~\"$Pod\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{cluster=~\"$cluster\",pod=~\"$Pod\",namespace=~\"$NameSpace\",container =~\"$Container\"}) by(pod) *8",
     "legendFormat": "Inflow:{{ pod}}"
    },
    {
     "expr": "max(max(irate(container_network_transmit_bytes_total{cluster=~\"$cluster\",pod=~\"$Pod\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{cluster=~\"$cluster\",pod=~\"$Pod\",namespace=~\"$NameSpace\",container =~\"$Container\"}) by(pod) *8",
     "legendFormat": "Outflow:{{ pod}}"
    }
   ]
  },
  {
   "title": "Pod Containers CPU Core Usage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(irate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (container, pod,node,namespace)",
     "legendFormat": "CPU Usage：{{ pod }}"
    },
    {
     "expr": "max(max(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"cpu\", unit=\"core\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)) by(container)",
     "legendFormat": "Pod CPU Limitations：{{ container }}"
    },
    {
     "expr": "max(max(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"cpu\", unit=\"core\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)) by(container)",
     "legendFormat": "Pod CPU Requests：{{ container }}"
    }
   ]
  },
  {
   "title": "Pod Containers WSS Memory Usage (Associable Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max (container_memory_working_set_bytes{cluster=~\"$cluster\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)",
     "legendFormat": "WSS：{{ pod }}"
    },
    {
     "expr": "max(max(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"memory\", unit=\"byte\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)) by(container)",
     "legendFormat": "Pod Memory Limits：{{ container }}"
    },
    {
     "expr": "max(max(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"memory\", unit=\"byte\",pod=~\"$Pod\",container =~\"$Container\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container,pod,node,namespace)) by(container)",
     "legendFormat": "Pod Memory Requests：{{ container }}"
    }
   ]
  },
  {
   "title": "Pod Containers RSS Memory Usage (Associable Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max (container_memory_rss{cluster=~\"$cluster\",pod=~\"$Pod\",container =~\"$Container\",container !=\"\",container!=\"POD\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}) by (container, pod,node,namespace)",
     "legendFormat": "RSS：{{ pod }}"
    }
   ]
  },
  {
   "title": "CPU Throttling percentage",
   "type": "timeseries",
   "description": "CPU throttling (limiting) in Kubernetes is considered problematic, or “bad,” when it starts affecting application latency and performance. This typically becomes noticeable when sustained values exceed 5%–10% of available CPU time.\nAlthough any value above zero indicates that the container has been artificially paused by the Linux scheduler (CFS), the usual alert thresholds are:\n\n< 5% (Normal): Acceptable. Small spikes in throttling may occur due to the nature of the Completely Fair Scheduler (CFS).\n10% – 20% (Concerning): Indicates the application is frequently hitting its limit. Intermittent latency is likely.\n> 20% (High): Will noticeably impact performance. The application is being severely restricted even if the node might still have idle CPU capacity.\n\n\nWhy is throttling bad?\nThrottling pauses the process when the configured CPU limit (limits.cpu) is reached, even if the node still has available CPU. This causes “random slowness” and latency spikes, not because the CPU is saturated, but because Kubernetes is enforcing a usage cap.\n\nRecommendations to avoid it\n\nPrioritize Requests over Limits: Properly configure requests.cpu to guarantee resources, and consider not setting CPU limits (or setting them very high) for standard workloads, allowing applications to use available CPU.\nMonitor container_cpu_cfs_throttled_seconds_total: Use Prometheus to track this metric.\nAdjust limits: If throttling is high, increase or remove the CPU limit if cost containment is not a concern.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_cfs_throttled_periods_total{cluster=\"$cluster\", namespace=~\"$NameSpace\", pod=~\"$Pod\", container=~\"$Container\", container!=\"\"}[5m]) /\r\nrate(container_cpu_cfs_periods_total{cluster=\"$cluster\", namespace=~\"$NameSpace\", pod=~\"$Pod\", container=~\"$Container\", container!=\"\"}[5m]) * 100",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Throttling percentage (>50%)",
   "type": "timeseries",
   "description": "CPU throttling (limiting) in Kubernetes is considered problematic, or “bad,” when it starts affecting application latency and performance. This typically becomes noticeable when sustained values exceed 5%–10% of available CPU time.\nAlthough any value above zero indicates that the container has been artificially paused by the Linux scheduler (CFS), the usual alert thresholds are:\n\n< 5% (Normal): Acceptable. Small spikes in throttling may occur due to the nature of the Completely Fair Scheduler (CFS).\n10% – 20% (Concerning): Indicates the application is frequently hitting its limit. Intermittent latency is likely.\n> 20% (High): Will noticeably impact performance. The application is being severely restricted even if the node might still have idle CPU capacity.\n\n\nWhy is throttling bad?\nThrottling pauses the process when the configured CPU limit (limits.cpu) is reached, even if the node still has available CPU. This causes “random slowness” and latency spikes, not because the CPU is saturated, but because Kubernetes is enforcing a usage cap.\n\nRecommendations to avoid it\n\nPrioritize Requests over Limits: Properly configure requests.cpu to guarantee resources, and consider not setting CPU limits (or setting them very high) for standard workloads, allowing applications to use available CPU.\nMonitor container_cpu_cfs_throttled_seconds_total: Use Prometheus to track this metric.\nAdjust limits: If throttling is high, increase or remove the CPU limit if cost containment is not a concern.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n    rate(container_cpu_cfs_throttled_periods_total{cluster=\"$cluster\", namespace=~\"$NameSpace\", pod=~\"$Pod\", container=~\"$Container\", container!=\"\"}[5m]) /\r\n    rate(container_cpu_cfs_periods_total{cluster=\"$cluster\", namespace=~\"$NameSpace\", pod=~\"$Pod\", container=~\"$Container\", container!=\"\"}[5m]) * 100\r\n) > 50",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "CPU Throttling percentage (20%-50%)",
   "type": "timeseries",
   "description": "CPU throttling (limiting) in Kubernetes is considered problematic, or “bad,” when it starts affecting application latency and performance. This typically becomes noticeable when sustained values exceed 5%–10% of available CPU time.\nAlthough any value above zero indicates that the container has been artificially paused by the Linux scheduler (CFS), the usual alert thresholds are:\n\n< 5% (Normal): Acceptable. Small spikes in throttling may occur due to the nature of the Completely Fair Scheduler (CFS).\n10% – 20% (Concerning): Indicates the application is frequently hitting its limit. Intermittent latency is likely.\n> 20% (High): Will noticeably impact performance. The application is being severely restricted even if the node might still have idle CPU capacity.\n\n\nWhy is throttling bad?\nThrottling pauses the process when the configured CPU limit (limits.cpu) is reached, even if the node still has available CPU. This causes “random slowness” and latency spikes, not because the CPU is saturated, but because Kubernetes is enforcing a usage cap.\n\nRecommendations to avoid it\n\nPrioritize Requests over Limits: Properly configure requests.cpu to guarantee resources, and consider not setting CPU limits (or setting them very high) for standard workloads, allowing applications to use available CPU.\nMonitor container_cpu_cfs_throttled_seconds_total: Use Prometheus to track this metric.\nAdjust limits: If throttling is high, increase or remove the CPU limit if cost containment is not a concern.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(\r\n    rate(container_cpu_cfs_throttled_periods_total{cluster=\"$cluster\", namespace=~\"$NameSpace\", pod=~\"$Pod\", container=~\"$Container\", container!=\"\"}[5m]) /\r\n    rate(container_cpu_cfs_periods_total{cluster=\"$cluster\", namespace=~\"$NameSpace\", pod=~\"$Pod\", container=~\"$Container\", container!=\"\"}[5m]) * 100\r\n) > 20\r\nand\r\n(\r\n    rate(container_cpu_cfs_throttled_periods_total{cluster=\"$cluster\", namespace=~\"$NameSpace\", pod=~\"$Pod\", container=~\"$Container\", container!=\"\"}[5m]) /\r\n    rate(container_cpu_cfs_periods_total{cluster=\"$cluster\", namespace=~\"$NameSpace\", pod=~\"$Pod\", container=~\"$Container\", container!=\"\"}[5m]) * 100\r\n) < 50",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Microservices (Container Name) Resource Overview：Selected Microservices:【$Container】",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 76 }
  },
  {
   "title": "Microservices (Container Name) Resource Statistics",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container) / (sum(container_spec_cpu_quota{cluster=~\"$cluster\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}/100000) by (container))"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container)",
     "legendFormat": "Total Cores Used"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"cpu\", unit=\"core\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"cpu\", unit=\"core\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=~\"$cluster\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)/ sum(container_spec_memory_limit_bytes{cluster=~\"$cluster\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
    },
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=~\"$cluster\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
    },
    {
     "expr": "sum (container_memory_rss{cluster=~\"$cluster\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)/ sum(container_spec_memory_limit_bytes{cluster=~\"$cluster\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
     "legendFormat": "Average Memory%(RSS)"
    },
    {
     "expr": "sum (container_memory_rss{cluster=~\"$cluster\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
     "legendFormat": "Total Memory Usage (RSS) "
    },
    {
     "expr": "sum by(container) (kube_pod_container_resource_requests{cluster=~\"$cluster\",resource=\"memory\", unit=\"byte\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"})"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"memory\", unit=\"byte\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
    },
    {
     "expr": "avg(container_fs_usage_bytes{cluster=~\"$cluster\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
    },
    {
     "expr": "count(kube_pod_container_info{cluster=~\"$cluster\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by(container,namespace)"
    },
    {
     "expr": "avg(container_fs_limit_bytes{cluster=~\"$cluster\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)"
    }
   ]
  },
  {
   "title": "Microservices (Container Name) Average CPU Usage (Maximum100%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container) / (sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"cpu\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)) * 100",
     "legendFormat": "{{ container}}"
    }
   ]
  },
  {
   "title": "Microservice (Container Name) Average Memory Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=~\"$cluster\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)/ sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"memory\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container) * 100",
     "legendFormat": "WSS：{{ container }}"
    },
    {
     "expr": "sum (container_memory_rss{cluster=~\"$cluster\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)/ sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"memory\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container) * 100",
     "legendFormat": "RSS：{{ container }}"
    }
   ]
  },
  {
   "title": "Microservice (Container Name) Network bandwidth per second (Associable Nodes)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 86 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "sum(sum(irate(container_network_receive_bytes_total{cluster=~\"$cluster\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{cluster=~\"$cluster\",namespace=~\"$NameSpace\",container =~\"$Container\"}) by(container) *8",
     "legendFormat": "Inflow:{{ container }}"
    },
    {
     "expr": "sum(sum(irate(container_network_transmit_bytes_total{cluster=~\"$cluster\",node=~\"^$Node$\",namespace=~\"$NameSpace\"}[2m])) by (pod)* on(pod) group_right kube_pod_container_info{cluster=~\"$cluster\",namespace=~\"$NameSpace\",container =~\"$Container\"}) by(container) *8",
     "legendFormat": "Outflow:{{ container }}"
    }
   ]
  },
  {
   "title": "Microservices (Container Name) Overall CPU Cores Used",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_limits{cluster=~\"$cluster\",resource=\"cpu\", unit=\"core\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
     "legendFormat": "CPU Limitations：{{ container}}"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{cluster=~\"$cluster\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}[2m])) by (container)",
     "legendFormat": "CPU Core Usage：{{ container}}"
    }
   ]
  },
  {
   "title": "Microservices (Container Name) Overall Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{cluster=~\"$cluster\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
     "legendFormat": "WSS：{{ container }}"
    },
    {
     "expr": "sum(container_spec_memory_limit_bytes{cluster=~\"$cluster\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
     "legendFormat": "Memory Limit：{{ container }}"
    },
    {
     "expr": "sum (container_memory_rss{cluster=~\"$cluster\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by (container)",
     "legendFormat": "RSS：{{ container }}"
    }
   ]
  },
  {
   "title": "Microservice (Container Name) Pod Number",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(kube_pod_container_info{cluster=~\"$cluster\",container =~\"$Container\",container !=\"\",container!=\"POD\",namespace=~\"$NameSpace\"}) by(container,namespace)",
     "legendFormat": "{{namespace}}：{{ container }}"
    }
   ]
  }
 ]
}