{
 "title": "Loki / Reads Resources",
 "tags": [ "loki" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "app_instance",
    "label": "app_instance",
    "query": "label_values(loki_build_info, app_instance)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(loki_build_info{app_instance=~\"$app_instance\"}, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Query Frontend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container=~\"query-frontend\", pod=~\"^$app_instance(-.*)?$\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{namespace=~\"$namespace\", container=~\"query-frontend\", resource=\"cpu\", pod=~\"^$app_instance(-.*)?$\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{namespace=~\"$namespace\", container=~\"query-frontend\", resource=\"cpu\", pod=~\"^$app_instance(-.*)?$\"} > 0)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{namespace=~\"$namespace\", container=~\"query-frontend\", pod=~\"^$app_instance(-.*)?$\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{namespace=~\"$namespace\", container=~\"query-frontend\", resource=\"memory\", pod=~\"^$app_instance(-.*)?$\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{namespace=~\"$namespace\", container=~\"query-frontend\", resource=\"memory\", pod=~\"^$app_instance(-.*)?$\"} > 0)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{app_instance=~\"$app_instance\", job=~\"($namespace)/.*-query-frontend\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Query Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container=\"query-scheduler\", pod=~\"^$app_instance(-.*)?$\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{namespace=~\"$namespace\", container=\"query-scheduler\", resource=\"cpu\", pod=~\"^$app_instance(-.*)?$\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{namespace=~\"$namespace\", container=\"query-scheduler\", resource=\"cpu\", pod=~\"^$app_instance(-.*)?$\"} > 0)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{namespace=~\"$namespace\", container=~\"query-scheduler\", pod=~\"^$app_instance(-.*)?$\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{namespace=~\"$namespace\", container=~\"query-scheduler\", resource=\"memory\", pod=~\"^$app_instance(-.*)?$\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{namespace=~\"$namespace\", container=~\"query-scheduler\", resource=\"memory\", pod=~\"^$app_instance(-.*)?$\"} > 0)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{app_instance=~\"$app_instance\", job=~\"($namespace)/.*-query-scheduler\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  { "title": "Querier", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container=\"querier\", pod=~\"^$app_instance(-.*)?$\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{namespace=~\"$namespace\", container=\"querier\", resource=\"cpu\", pod=~\"^$app_instance(-.*)?$\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{namespace=~\"$namespace\", container=\"querier\", resource=\"cpu\", pod=~\"^$app_instance(-.*)?$\"} > 0)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{namespace=~\"$namespace\", container=~\"querier\", pod=~\"^$app_instance(-.*)?$\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{namespace=~\"$namespace\", container=~\"querier\", resource=\"memory\", pod=~\"^$app_instance(-.*)?$\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{namespace=~\"$namespace\", container=~\"querier\", resource=\"memory\", pod=~\"^$app_instance(-.*)?$\"} > 0)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{app_instance=~\"$app_instance\", job=~\"($namespace)/.*-querier\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance, device) (rate(node_disk_written_bytes_total[$__rate_interval])) + ignoring(pod) group_right() (label_replace(count by(instance, pod, device) (container_fs_writes_bytes_total{namespace=~\"$namespace\", container=\"querier\", device!~\".*sda.*\"}), \"device\", \"$1\", \"device\", \"/dev/(.*)\") * 0)\n",
     "legendFormat": "{{pod}} - {{device}}"
    }
   ]
  },
  {
   "title": "Disk Reads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance,device) (rate(node_disk_read_bytes_total[$__rate_interval])) + ignoring(pod) group_right() (label_replace(count by(instance, pod, device) (container_fs_writes_bytes_total{app_instance=~\"$app_instance\", namespace=~\"$namespace\", container=\"querier\", device!~\".*sda.*\"}), \"device\", \"$1\", \"device\", \"/dev/(.*)\") * 0)\n",
     "legendFormat": "{{pod}} - {{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\".*querier.*\"} / kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\".*querier.*\"})",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  { "title": "Index Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container=\"index-gateway\", pod=~\"^$app_instance(-.*)?$\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{namespace=~\"$namespace\", container=\"index-gateway\", resource=\"cpu\", pod=~\"^$app_instance(-.*)?$\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{namespace=~\"$namespace\", container=\"index-gateway\", resource=\"cpu\", pod=~\"^$app_instance(-.*)?$\"} > 0)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{namespace=~\"$namespace\", container=\"index-gateway\", pod=~\"^$app_instance(-.*)?$\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{namespace=~\"$namespace\", container=\"index-gateway\", resource=\"memory\", pod=~\"^$app_instance(-.*)?$\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{namespace=~\"$namespace\", container=\"index-gateway\", resource=\"memory\", pod=~\"^$app_instance(-.*)?$\"} > 0)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{app_instance=~\"$app_instance\", job=~\"($namespace)/(.*index-gateway.*|loki)\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance, device) (rate(node_disk_written_bytes_total[$__rate_interval])) + ignoring(pod) group_right() (label_replace(count by(instance, pod, device) (container_fs_writes_bytes_total{app_instance=~\"$app_instance\", namespace=~\"$namespace\", container=~\"loki|index-gateway\", pod=~\"(.*index-gateway.*|loki)\", device!~\".*sda.*\"}), \"device\", \"$1\", \"device\", \"/dev/(.*)\") * 0)\n",
     "legendFormat": "{{pod}} - {{device}}"
    }
   ]
  },
  {
   "title": "Disk Reads",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum by(instance, device) (rate(node_disk_read_bytes_total[$__rate_interval])) + ignoring(pod) group_right() (label_replace(count by(instance, pod, device) (container_fs_writes_bytes_total{namespace=~\"$namespace\", container=\"index-gateway\", pod=~\"(.*index-gateway.*)\", device!~\".*sda.*\"}), \"device\", \"$1\", \"device\", \"/dev/(.*)\") * 0)\n",
     "legendFormat": "{{pod}} - {{device}}"
    }
   ]
  },
  {
   "title": "Disk Space Utilization",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max by(persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\".*(.*index-gateway.*).*\"} / kubelet_volume_stats_capacity_bytes{namespace=~\"$namespace\", persistentvolumeclaim=~\".*(.*index-gateway.*).*\"})",
     "legendFormat": "{{persistentvolumeclaim}}"
    }
   ]
  },
  { "title": "Ingester", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container=\"ingester\", pod=~\"^$app_instance(-.*)?$\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{namespace=~\"$namespace\", container=\"ingester\", resource=\"cpu\", pod=~\"^$app_instance(-.*)?$\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{namespace=~\"$namespace\", container=\"ingester\", resource=\"cpu\", pod=~\"^$app_instance(-.*)?$\"} > 0)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (workingset)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by(pod) (container_memory_working_set_bytes{namespace=~\"$namespace\", container=\"ingester\", pod=~\"^$app_instance(-.*)?$\"})",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{namespace=~\"$namespace\", container=\"ingester\", resource=\"memory\", pod=~\"^$app_instance(-.*)?$\"} > 0)",
     "legendFormat": "request"
    },
    {
     "expr": "min(kube_pod_container_resource_limits{namespace=~\"$namespace\", container=\"ingester\", resource=\"memory\", pod=~\"^$app_instance(-.*)?$\"} > 0)",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Memory (go heap inuse)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{app_instance=~\"$app_instance\", job=~\"($namespace)/(.*ingester.*|loki)\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Ruler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rules",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(pod) (loki_prometheus_rule_group_rules{app_instance=~\"$app_instance\", job=~\"($namespace)/.*-ruler\"}) or sum by(pod) (cortex_prometheus_rule_group_rules{app_instance=~\"$app_instance\", job=~\"($namespace)/.*-ruler\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(pod) (rate(container_cpu_usage_seconds_total{namespace=~\"$namespace\", container=\"ruler\", pod=~\"^$app_instance(-.*)?$\"}[$__rate_interval]))",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{namespace=~\"$namespace\", container=\"ruler\", resource=\"cpu\", pod=~\"^$app_instance(-.*)?$\"} > 0)",
       "legendFormat": "request"
      },
      {
       "expr": "min(kube_pod_container_resource_limits{namespace=~\"$namespace\", container=\"ruler\", resource=\"cpu\", pod=~\"^$app_instance(-.*)?$\"} > 0)",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Memory (workingset)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by(pod) (container_memory_working_set_bytes{app_instance=~\"$app_instance\", namespace=~\"$namespace\", container=~\"ruler\"})",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{app_instance=~\"$app_instance\", namespace=~\"$namespace\", container=~\"ruler\", resource=\"memory\"} > 0)",
       "legendFormat": "request"
      },
      {
       "expr": "min(container_spec_memory_limit_bytes{app_instance=~\"$app_instance\", namespace=~\"$namespace\", container=~\"ruler\"} > 0)",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Memory (go heap inuse)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum by(pod) (go_memstats_heap_inuse_bytes{app_instance=~\"$app_instance\", job=~\"($namespace)/.*-ruler\"})",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  }
 ]
}