{
 "title": "Loki Resources / Overview (+ Requests)",
 "description": "This dashboard provides a resource usage overview of the Loki components Querier, Query Frontend, Query Scheduler, Distributor, Ingester, Pattern Ingester, Index Gateway, Compactor and Ruler.\r\n\r\nIt includes CPU and Memory requests, limits and usage. In addition, the last termination reason is plotted.",
 "tags": [ "loki" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 0 },
   "options": {
    "content": "![logo](https://grafana.com/media/docs/loki/logo-grafana-loki.png)"
   }
  },
  {
   "title": "Number of Pods",
   "type": "stat",
   "gridPos": { "h": 7, "w": 21, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "\r\nsort_desc(\r\n  sum by (component) (\r\n    label_replace(\r\n      kube_pod_info{\r\n        pod=~\"loki-(compactor|index-gateway|ruler|ingester|distributor|query-frontend|querier|pattern-ingester|query-scheduler).*\",\r\n        container!=\"\"\r\n      },\r\n      \"component\", \"$1\", \"pod\",\r\n      \"loki-(compactor|index-gateway|ruler|ingester|distributor|query-frontend|querier|pattern-ingester|query-scheduler).*\"\r\n    )\r\n  )\r\n)\r\n",
     "legendFormat": "{{app_kubernetes_io_component}}"
    }
   ]
  },
  { "title": "Loki / Querier", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 } },
  {
   "title": "CPU Core Usage vs. Request & Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      resource=\"cpu\",\r\n      namespace=\"monitoring\",\r\n      pod=~\"loki-querier.*\",\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "limit"
    },
    {
     "expr": "max by (pod) (\r\n  irate(container_cpu_usage_seconds_total{container=\"querier\", pod=~\"loki.*\"}[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      resource=\"cpu\",\r\n      namespace=\"monitoring\",\r\n      pod=~\"loki-querier.*\",\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory Usage vs. Request & Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "min(kube_pod_container_resource_limits{container=\"querier\", resource=\"memory\", pod=~\"loki.*\"} > 0)",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{container=\"querier\", pod=~\"loki.*\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{container=\"querier\", resource=\"memory\", pod=~\"loki.*\"} > 0)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{\r\n  pod=~\"loki-querier.*\",\r\n} != 0\r\n",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  { "title": "Loki / Query Frontend", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "CPU Core Usage vs. Request & Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      resource=\"cpu\",\r\n      namespace=\"monitoring\",\r\n      pod=~\"loki-query-frontend.*\",\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "limit"
    },
    {
     "expr": "max by (pod) (\r\n  irate(container_cpu_usage_seconds_total{container=\"query-frontend\", pod=~\"loki-query-frontend.*\"}[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      resource=\"cpu\",\r\n      namespace=\"monitoring\",\r\n      pod=~\"loki-query-frontend.*\",\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory Usage vs. Request & Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "min(kube_pod_container_resource_limits{container=\"query-frontend\", resource=\"memory\", pod=~\"loki-query-frontend.*\"} > 0)",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{container=\"query-frontend\", pod=~\"loki-query-frontend.*\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{container=\"query-frontend\", resource=\"memory\", pod=~\"loki-query-frontend.*\"} > 0)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{\r\n  pod=~\"loki-query-frontend.*\",\r\n} != 0\r\n",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  { "title": "Loki / Query Scheduler", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "CPU Core Usage vs. Request & Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      resource=\"cpu\",\r\n      namespace=\"monitoring\",\r\n      pod=~\"loki-query-scheduler.*\",\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "limit"
    },
    {
     "expr": "max by (pod) (\r\n  irate(container_cpu_usage_seconds_total{container=\"query-scheduler\", pod=~\"loki-query-scheduler.*\"}[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      resource=\"cpu\",\r\n      namespace=\"monitoring\",\r\n      pod=~\"loki-query-scheduler.*\",\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory Usage vs. Request & Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "min(kube_pod_container_resource_limits{container=\"query-scheduler\", resource=\"memory\", pod=~\"loki-query-scheduler.*\"} > 0)",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{container=\"query-scheduler\", pod=~\"loki-query-scheduler.*\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{container=\"query-scheduler\", resource=\"memory\", pod=~\"loki-query-scheduler.*\"} > 0)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{\r\n  pod=~\"loki-query-scheduler.*\",\r\n} != 0\r\n",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  { "title": "Loki / Distributor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "CPU Core Usage vs. Request & Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      resource=\"cpu\",\r\n      namespace=\"monitoring\",\r\n      pod=~\"loki-distributor.*\",\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "limit"
    },
    {
     "expr": "max by (pod) (\r\n  irate(container_cpu_usage_seconds_total{container=\"distributor\", pod=~\"loki-distributor.*\"}[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      resource=\"cpu\",\r\n      namespace=\"monitoring\",\r\n      pod=~\"loki-distributor.*\",\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory Usage vs. Request & Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "min(kube_pod_container_resource_limits{container=\"distributor\", resource=\"memory\", pod=~\"loki-distributor.*\"} > 0)",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{container=\"distributor\", pod=~\"loki-distributor.*\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{container=\"distributor\", resource=\"memory\", pod=~\"loki-distributor.*\"} > 0)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{\r\n  pod=~\"loki-distributor.*\",\r\n} != 0\r\n",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  { "title": "Loki / Ingester", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "CPU Core Usage vs. Request & Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      resource=\"cpu\",\r\n      namespace=\"monitoring\",\r\n      pod=~\"loki-ingester.*\",\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "limit"
    },
    {
     "expr": "max by (pod) (\r\n  irate(container_cpu_usage_seconds_total{container=\"ingester\", pod=~\"loki-ingester.*\"}[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      resource=\"cpu\",\r\n      namespace=\"monitoring\",\r\n      pod=~\"loki-ingester.*\",\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory Usage vs. Request & Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "min(kube_pod_container_resource_limits{container=\"ingester\", resource=\"memory\", pod=~\"loki-ingester.*\"} > 0)",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{container=\"ingester\", pod=~\"loki-ingester.*\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{container=\"ingester\", resource=\"memory\", pod=~\"loki-ingester.*\"} > 0)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{\r\n  pod=~\"loki-ingester.*\",\r\n} != 0\r\n",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  { "title": "Loki / Pattern Ingester", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "CPU Core Usage vs. Request & Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      resource=\"cpu\",\r\n      namespace=\"monitoring\",\r\n      pod=~\"loki-pattern-ingester.*\",\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "limit"
    },
    {
     "expr": "max by (pod) (\r\n  irate(container_cpu_usage_seconds_total{container=\"pattern-ingester\", pod=~\"loki-pattern-ingester.*\"}[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      resource=\"cpu\",\r\n      namespace=\"monitoring\",\r\n      pod=~\"loki-pattern-ingester.*\",\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory Usage vs. Request & Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "min(kube_pod_container_resource_limits{container=\"pattern-ingester\", resource=\"memory\", pod=~\"loki-pattern-ingester.*\"} > 0)",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{container=\"pattern-ingester\", pod=~\"loki-pattern-ingester.*\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{container=\"pattern-ingester\", resource=\"memory\", pod=~\"loki-pattern-ingester.*\"} > 0)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 53 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{\r\n  pod=~\"loki-pattern-ingester.*\",\r\n} != 0\r\n",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  { "title": "Loki / Index Gateway", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "CPU Core Usage vs. Request & Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      resource=\"cpu\",\r\n      namespace=\"monitoring\",\r\n      pod=~\"loki-index-gateway.*\",\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "limit"
    },
    {
     "expr": "max by (pod) (\r\n  irate(container_cpu_usage_seconds_total{container=\"index-gateway\", pod=~\"loki-index-gateway.*\"}[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      resource=\"cpu\",\r\n      namespace=\"monitoring\",\r\n      pod=~\"loki-index-gateway.*\",\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory Usage vs. Request & Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "min(kube_pod_container_resource_limits{container=\"index-gateway\", resource=\"memory\", pod=~\"loki-index-gateway.*\"} > 0)",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{container=\"index-gateway\", pod=~\"loki-index-gateway.*\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{container=\"index-gateway\", resource=\"memory\", pod=~\"loki-index-gateway.*\"} > 0)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{\r\n  pod=~\"loki-index-gateway.*\",\r\n} != 0\r\n",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  { "title": "Loki / Compactor", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 } },
  {
   "title": "CPU Core Usage vs. Request & Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      resource=\"cpu\",\r\n      namespace=\"monitoring\",\r\n      pod=~\"loki-compactor.*\",\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "limit"
    },
    {
     "expr": "max by (pod) (\r\n  irate(container_cpu_usage_seconds_total{container=\"compactor\", pod=~\"loki-compactor.*\"}[$__interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      resource=\"cpu\",\r\n      namespace=\"monitoring\",\r\n      pod=~\"loki-compactor.*\",\r\n    }\r\n  )\r\n)\r\n",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Memory Usage vs. Request & Limit",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 10, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "min(kube_pod_container_resource_limits{container=\"compactor\", resource=\"memory\", pod=~\"loki-compactor.*\"} > 0)",
     "legendFormat": "limit"
    },
    {
     "expr": "sum(max_over_time(container_memory_working_set_bytes{container=\"compactor\", pod=~\"loki-compactor.*\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "min(kube_pod_container_resource_requests{container=\"compactor\", resource=\"memory\", pod=~\"loki-compactor.*\"} > 0)",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Last Terminated Reason",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 71 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "kube_pod_container_status_last_terminated_reason{\r\n  pod=~\"loki-compactor.*\",\r\n} != 0\r\n",
     "legendFormat": "{{reason}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Loki / Ruler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Core Usage vs. Request & Limit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_limits{\r\n      resource=\"cpu\",\r\n      namespace=\"monitoring\",\r\n      pod=~\"loki-ruler.*\",\r\n    }\r\n  )\r\n)\r\n",
       "legendFormat": "limit"
      },
      {
       "expr": "max by (pod) (\r\n  irate(container_cpu_usage_seconds_total{container=\"ruler\", pod=~\"loki-ruler.*\"}[$__interval]))",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(\r\n  sum by (pod) (\r\n    kube_pod_container_resource_requests{\r\n      resource=\"cpu\",\r\n      namespace=\"monitoring\",\r\n      pod=~\"loki-ruler.*\",\r\n    }\r\n  )\r\n)\r\n",
       "legendFormat": "request"
      }
     ]
    },
    {
     "title": "Memory Usage vs. Request & Limit",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 10, "x": 10, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "min(kube_pod_container_resource_limits{container=\"ruler\", resource=\"memory\", pod=~\"loki-ruler.*\"} > 0)",
       "legendFormat": "limit"
      },
      {
       "expr": "sum(max_over_time(container_memory_working_set_bytes{container=\"ruler\", pod=~\"loki-ruler.*\"}[$__interval])) by (pod)",
       "legendFormat": "{{pod}}"
      },
      {
       "expr": "min(kube_pod_container_resource_requests{container=\"ruler\", resource=\"memory\", pod=~\"loki-ruler.*\"} > 0)",
       "legendFormat": "request"
      }
     ]
    },
    {
     "title": "Last Terminated Reason",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 80 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "kube_pod_container_status_last_terminated_reason{\r\n  pod=~\"loki-ruler.*\",\r\n} != 0\r\n",
       "legendFormat": "{{reason}} - {{pod}}"
      }
     ]
    }
   ]
  }
 ]
}